#!/bin/bash
# Quick start script for IIT Madras BS Learning

echo "🎓 IIT Madras BS Data Science Learning Environment"
echo "=================================================="
echo ""
echo "✅ Virtual environment created: .venv"
echo "✅ 40+ packages installed"
echo "✅ Ready for all Foundation courses!"
echo ""
echo "📝 Quick Start:"
echo ""
echo "  1. Activate environment:"
echo "     source activate.sh"
echo ""
echo "  2. Start Jupyter:"
echo "     jupyter lab"
echo ""
echo "  3. Open any notebook:"
echo "     - 01-Foundation-Level/01-Mathematics/notebooks/week-01-practice.ipynb"
echo ""
echo "  4. When done:"
echo "     deactivate"
echo ""
echo "📚 Documentation:"
echo "   - VENV_SETUP.md - Complete setup guide"
echo "   - requirements.txt - All packages"
echo "   - CONTENT_CREATION_STRATEGY.md - Content roadmap"
echo ""
echo "🚀 Happy Learning!"
