#!/usr/bin/env python3
"""
Generate enhanced Week 3 notebook: Numerical Data Visualization
Following the quality pattern of weeks 4-12
"""

import json

def create_week3_notebook():
    notebook = {
        "cells": [],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.9.6"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 5
    }
    
    cells = [
        # Cell 1: Title
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Week 3: Numerical Data Visualization\n",
                "\n",
                "**Course:** Statistics I (BSMA1002)  \n",
                "**Level:** Foundation  \n",
                "**Week:** 3\n",
                "\n",
                "## Topics Covered\n",
                "1. Histograms and frequency distributions\n",
                "2. Box plots and five-number summary\n",
                "3. Stem-and-leaf plots\n",
                "4. Dot plots and distribution shapes\n",
                "5. Identifying skewness and outliers\n",
                "\n",
                "## Learning Objectives\n",
                "- Create and interpret histograms for numerical data\n",
                "- Understand distribution shapes and patterns\n",
                "- Use box plots to identify outliers and spread\n",
                "- Analyze data using multiple visualization techniques\n"
            ]
        },
        
        # Cell 2: Imports
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Import required libraries\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "import matplotlib.pyplot as plt\n",
                "import seaborn as sns\n",
                "from scipy import stats\n",
                "\n",
                "# Set random seed\n",
                "np.random.seed(42)\n",
                "\n",
                "# Configure visualizations\n",
                "plt.style.use('seaborn-v0_8-whitegrid')\n",
                "sns.set_palette('Set2')\n",
                "%matplotlib inline\n",
                "\n",
                "print('✓ Libraries loaded successfully')"
            ]
        },
        
        # Cell 3: Theory - Histograms
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 1. Histograms\n",
                "\n",
                "### Definition\n",
                "A **histogram** displays the frequency distribution of numerical data using adjacent bars.\n",
                "\n",
                "### Components\n",
                "1. **Bins (Classes)**: Intervals that divide the data range\n",
                "2. **Frequency**: Count of observations in each bin\n",
                "3. **Height**: Represents frequency (or density)\n",
                "4. **No gaps**: Bars are adjacent (continuous data)\n",
                "\n",
                "### Choosing Number of Bins\n",
                "\n",
                "**Sturges' Rule:**\n",
                "$$k = 1 + \\lceil \\log_2(n) \\rceil$$\n",
                "\n",
                "**Square Root Rule:**\n",
                "$$k = \\lceil \\sqrt{n} \\rceil$$\n",
                "\n",
                "**Rice Rule:**\n",
                "$$k = \\lceil 2n^{1/3} \\rceil$$\n",
                "\n",
                "where $k$ = number of bins, $n$ = number of observations\n",
                "\n",
                "### Histogram vs Bar Chart\n",
                "| Feature | Histogram | Bar Chart |\n",
                "|---------|-----------|----------|\n",
                "| Data Type | Numerical (continuous) | Categorical |\n",
                "| Bars | Adjacent (no gaps) | Separated (gaps) |\n",
                "| X-axis | Intervals | Categories |\n",
                "| Reordering | Not allowed | Allowed |\n"
            ]
        },
        
        # Cell 4: Histogram Example
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Generate sample data - exam scores\n",
                "scores = np.random.normal(loc=75, scale=12, size=200)\n",
                "scores = np.clip(scores, 0, 100)  # Clip to valid range\n",
                "\n",
                "# Calculate optimal bins using different methods\n",
                "n = len(scores)\n",
                "sturges_bins = int(np.ceil(1 + np.log2(n)))\n",
                "sqrt_bins = int(np.ceil(np.sqrt(n)))\n",
                "rice_bins = int(np.ceil(2 * n**(1/3)))\n",
                "\n",
                "print(f'Data: {n} exam scores')\n",
                "print(f'\\nBin calculations:')\n",
                "print(f'  Sturges rule: {sturges_bins} bins')\n",
                "print(f'  Square root: {sqrt_bins} bins')\n",
                "print(f'  Rice rule: {rice_bins} bins')\n",
                "\n",
                "# Create histograms with different bin counts\n",
                "fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n",
                "\n",
                "bins_options = [sturges_bins, sqrt_bins, rice_bins, 20]\n",
                "titles = ['Sturges Rule', 'Square Root Rule', 'Rice Rule', 'Fixed (20 bins)']\n",
                "\n",
                "for ax, bins, title in zip(axes.flat, bins_options, titles):\n",
                "    ax.hist(scores, bins=bins, edgecolor='black', color='steelblue', alpha=0.7)\n",
                "    ax.set_title(f'{title} ({bins} bins)', fontsize=12, fontweight='bold')\n",
                "    ax.set_xlabel('Exam Score', fontsize=10)\n",
                "    ax.set_ylabel('Frequency', fontsize=10)\n",
                "    ax.axvline(scores.mean(), color='red', linestyle='--', linewidth=2, label=f'Mean: {scores.mean():.1f}')\n",
                "    ax.legend()\n",
                "    ax.grid(axis='y', alpha=0.3)\n",
                "\n",
                "plt.tight_layout()\n",
                "plt.show()\n",
                "\n",
                "print(f'\\nData summary: Mean={scores.mean():.1f}, Std={scores.std():.1f}')"
            ]
        },
        
        # Cell 5: Theory - Distribution Shapes
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 2. Distribution Shapes\n",
                "\n",
                "### Types of Distributions\n",
                "\n",
                "1. **Symmetric (Normal)**\n",
                "   - Bell-shaped curve\n",
                "   - Mean = Median = Mode\n",
                "   - Equal tails on both sides\n",
                "\n",
                "2. **Right-Skewed (Positively Skewed)**\n",
                "   - Tail extends to the right\n",
                "   - Mode < Median < Mean\n",
                "   - Most values concentrated on left\n",
                "\n",
                "3. **Left-Skewed (Negatively Skewed)**\n",
                "   - Tail extends to the left\n",
                "   - Mean < Median < Mode\n",
                "   - Most values concentrated on right\n",
                "\n",
                "### Skewness Measure\n",
                "$$\\text{Skewness} = \\frac{\\sum_{i=1}^{n}(x_i - \\bar{x})^3}{(n-1)s^3}$$\n",
                "\n",
                "- **Skewness = 0**: Symmetric\n",
                "- **Skewness > 0**: Right-skewed\n",
                "- **Skewness < 0**: Left-skewed\n",
                "\n",
                "### Kurtosis (Peakedness)\n",
                "- **Leptokurtic**: Heavy tails, sharp peak\n",
                "- **Mesokurtic**: Normal distribution\n",
                "- **Platykurtic**: Light tails, flat peak\n"
            ]
        },
        
        # Cell 6: Distribution Shapes Example
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Generate different distribution shapes\n",
                "np.random.seed(100)\n",
                "\n",
                "# Normal distribution\n",
                "normal_data = np.random.normal(50, 10, 1000)\n",
                "\n",
                "# Right-skewed (exponential-like)\n",
                "right_skewed = np.random.exponential(scale=20, size=1000) + 10\n",
                "\n",
                "# Left-skewed (reflected exponential)\n",
                "left_skewed = 100 - np.random.exponential(scale=20, size=1000)\n",
                "\n",
                "# Create comparison plot\n",
                "fig, axes = plt.subplots(1, 3, figsize=(15, 4))\n",
                "\n",
                "datasets = [normal_data, right_skewed, left_skewed]\n",
                "titles = ['Symmetric (Normal)', 'Right-Skewed', 'Left-Skewed']\n",
                "colors = ['#2E7D32', '#D32F2F', '#1976D2']\n",
                "\n",
                "for ax, data, title, color in zip(axes, datasets, titles, colors):\n",
                "    # Histogram\n",
                "    ax.hist(data, bins=30, edgecolor='black', color=color, alpha=0.6)\n",
                "    \n",
                "    # Statistics\n",
                "    mean_val = np.mean(data)\n",
                "    median_val = np.median(data)\n",
                "    skew_val = stats.skew(data)\n",
                "    \n",
                "    # Add vertical lines\n",
                "    ax.axvline(mean_val, color='red', linestyle='--', linewidth=2, label=f'Mean: {mean_val:.1f}')\n",
                "    ax.axvline(median_val, color='blue', linestyle=':', linewidth=2, label=f'Median: {median_val:.1f}')\n",
                "    \n",
                "    ax.set_title(f'{title}\\nSkewness: {skew_val:.2f}', fontsize=11, fontweight='bold')\n",
                "    ax.set_xlabel('Value', fontsize=10)\n",
                "    ax.set_ylabel('Frequency', fontsize=10)\n",
                "    ax.legend(fontsize=8)\n",
                "    ax.grid(axis='y', alpha=0.3)\n",
                "\n",
                "plt.tight_layout()\n",
                "plt.show()\n",
                "\n",
                "print('Interpretation:')\n",
                "print('  • Symmetric: Mean ≈ Median (both lines overlap)')\n",
                "print('  • Right-skewed: Mean > Median (red line to the right)')\n",
                "print('  • Left-skewed: Mean < Median (red line to the left)')"
            ]
        },
        
        # Cell 7: Theory - Box Plots
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 3. Box Plots (Box-and-Whisker Plots)\n",
                "\n",
                "### Five-Number Summary\n",
                "1. **Minimum**: Smallest value (excluding outliers)\n",
                "2. **Q1 (First Quartile)**: 25th percentile\n",
                "3. **Q2 (Median)**: 50th percentile\n",
                "4. **Q3 (Third Quartile)**: 75th percentile\n",
                "5. **Maximum**: Largest value (excluding outliers)\n",
                "\n",
                "### Box Plot Components\n",
                "- **Box**: Represents middle 50% of data (Q1 to Q3)\n",
                "- **Line in box**: Median (Q2)\n",
                "- **Whiskers**: Extend to min/max within 1.5×IQR\n",
                "- **Outliers**: Points beyond whiskers\n",
                "\n",
                "### IQR (Interquartile Range)\n",
                "$$\\text{IQR} = Q_3 - Q_1$$\n",
                "\n",
                "### Outlier Detection\n",
                "- **Lower fence**: $Q_1 - 1.5 \\times \\text{IQR}$\n",
                "- **Upper fence**: $Q_3 + 1.5 \\times \\text{IQR}$\n",
                "- Values outside fences are potential outliers\n",
                "\n",
                "### Advantages\n",
                "- Compact visualization of distribution\n",
                "- Easy outlier identification\n",
                "- Good for comparing multiple groups\n",
                "- Shows spread and central tendency\n"
            ]
        },
        
        # Cell 8: Box Plot Example
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Generate datasets with different characteristics\n",
                "np.random.seed(50)\n",
                "\n",
                "# Dataset with outliers\n",
                "data_with_outliers = np.concatenate([\n",
                "    np.random.normal(100, 15, 180),  # Main data\n",
                "    np.array([40, 45, 160, 170])      # Outliers\n",
                "])\n",
                "\n",
                "# Calculate five-number summary\n",
                "q1 = np.percentile(data_with_outliers, 25)\n",
                "q2 = np.percentile(data_with_outliers, 50)\n",
                "q3 = np.percentile(data_with_outliers, 75)\n",
                "iqr = q3 - q1\n",
                "lower_fence = q1 - 1.5 * iqr\n",
                "upper_fence = q3 + 1.5 * iqr\n",
                "\n",
                "print('Five-Number Summary:')\n",
                "print(f'  Minimum: {data_with_outliers.min():.1f}')\n",
                "print(f'  Q1 (25%): {q1:.1f}')\n",
                "print(f'  Median (Q2): {q2:.1f}')\n",
                "print(f'  Q3 (75%): {q3:.1f}')\n",
                "print(f'  Maximum: {data_with_outliers.max():.1f}')\n",
                "print(f'\\n  IQR: {iqr:.1f}')\n",
                "print(f'  Lower Fence: {lower_fence:.1f}')\n",
                "print(f'  Upper Fence: {upper_fence:.1f}')\n",
                "\n",
                "# Identify outliers\n",
                "outliers = data_with_outliers[(data_with_outliers < lower_fence) | (data_with_outliers > upper_fence)]\n",
                "print(f'\\n  Outliers detected: {len(outliers)}')\n",
                "print(f'  Outlier values: {sorted(outliers)}')\n",
                "\n",
                "# Create box plot\n",
                "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
                "\n",
                "# Box plot\n",
                "bp = axes[0].boxplot(data_with_outliers, vert=True, patch_artist=True,\n",
                "                     boxprops=dict(facecolor='lightblue', edgecolor='black'),\n",
                "                     medianprops=dict(color='red', linewidth=2),\n",
                "                     whiskerprops=dict(color='black', linewidth=1.5),\n",
                "                     capprops=dict(color='black', linewidth=1.5),\n",
                "                     flierprops=dict(marker='o', markerfacecolor='red', markersize=8, linestyle='none'))\n",
                "\n",
                "axes[0].set_ylabel('Value', fontsize=11)\n",
                "axes[0].set_title('Box Plot with Outliers', fontsize=13, fontweight='bold')\n",
                "axes[0].grid(axis='y', alpha=0.3)\n",
                "\n",
                "# Add annotations\n",
                "axes[0].text(1.15, q3, f'Q3: {q3:.1f}', fontsize=9, va='center')\n",
                "axes[0].text(1.15, q2, f'Median: {q2:.1f}', fontsize=9, va='center', color='red', fontweight='bold')\n",
                "axes[0].text(1.15, q1, f'Q1: {q1:.1f}', fontsize=9, va='center')\n",
                "\n",
                "# Histogram comparison\n",
                "axes[1].hist(data_with_outliers, bins=25, edgecolor='black', color='lightgreen', alpha=0.7)\n",
                "axes[1].axvline(q2, color='red', linestyle='--', linewidth=2, label='Median')\n",
                "axes[1].axvline(q1, color='blue', linestyle=':', linewidth=1.5, label='Q1')\n",
                "axes[1].axvline(q3, color='blue', linestyle=':', linewidth=1.5, label='Q3')\n",
                "axes[1].set_xlabel('Value', fontsize=11)\n",
                "axes[1].set_ylabel('Frequency', fontsize=11)\n",
                "axes[1].set_title('Histogram with Quartiles', fontsize=13, fontweight='bold')\n",
                "axes[1].legend()\n",
                "axes[1].grid(axis='y', alpha=0.3)\n",
                "\n",
                "plt.tight_layout()\n",
                "plt.show()"
            ]
        },
        
        # Cell 9: Comparing Multiple Groups
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Generate sales data for different regions\n",
                "np.random.seed(75)\n",
                "\n",
                "sales_data = {\n",
                "    'North': np.random.normal(150, 20, 100),\n",
                "    'South': np.random.normal(180, 25, 100),\n",
                "    'East': np.random.normal(140, 30, 100),\n",
                "    'West': np.random.normal(200, 15, 100)\n",
                "}\n",
                "\n",
                "df = pd.DataFrame(sales_data)\n",
                "\n",
                "# Create comparative visualizations\n",
                "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
                "\n",
                "# Multiple box plots\n",
                "df.boxplot(ax=axes[0], patch_artist=True, grid=False)\n",
                "axes[0].set_title('Regional Sales Comparison - Box Plots', fontsize=13, fontweight='bold')\n",
                "axes[0].set_xlabel('Region', fontsize=11)\n",
                "axes[0].set_ylabel('Sales (units)', fontsize=11)\n",
                "axes[0].grid(axis='y', alpha=0.3)\n",
                "\n",
                "# Overlapping histograms\n",
                "for region, color in zip(['North', 'South', 'East', 'West'], ['red', 'blue', 'green', 'orange']):\n",
                "    axes[1].hist(df[region], bins=20, alpha=0.4, label=region, edgecolor='black')\n",
                "\n",
                "axes[1].set_title('Regional Sales Distribution - Histograms', fontsize=13, fontweight='bold')\n",
                "axes[1].set_xlabel('Sales (units)', fontsize=11)\n",
                "axes[1].set_ylabel('Frequency', fontsize=11)\n",
                "axes[1].legend()\n",
                "axes[1].grid(axis='y', alpha=0.3)\n",
                "\n",
                "plt.tight_layout()\n",
                "plt.show()\n",
                "\n",
                "# Statistical summary\n",
                "print('Regional Sales Summary Statistics:')\n",
                "print('='*70)\n",
                "print(df.describe().round(1))\n",
                "print('\\nKey Observations:')\n",
                "print(f'  • Highest average: West ({df[\"West\"].mean():.1f} units)')\n",
                "print(f'  • Most consistent: West (std={df[\"West\"].std():.1f})')\n",
                "print(f'  • Most variable: East (std={df[\"East\"].std():.1f})')"
            ]
        },
        
        # Cell 10: Theory - Advanced Concepts
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 4. Additional Visualization Techniques\n",
                "\n",
                "### Density Plots (KDE)\n",
                "**Kernel Density Estimation** creates a smooth curve representing the probability density function.\n",
                "\n",
                "**Advantages:**\n",
                "- Smooth representation of distribution\n",
                "- No need to choose bin width\n",
                "- Better for comparing distributions\n",
                "\n",
                "### Violin Plots\n",
                "Combines box plot with KDE:\n",
                "- Width shows density at each value\n",
                "- Shows full distribution shape\n",
                "- Better than box plots for multimodal distributions\n",
                "\n",
                "### Cumulative Distribution Function (CDF)\n",
                "Shows proportion of data below each value:\n",
                "$$F(x) = P(X \\leq x)$$\n",
                "\n",
                "### Q-Q Plot (Quantile-Quantile)\n",
                "- Tests if data follows theoretical distribution\n",
                "- Points on straight line = good fit to distribution\n",
                "- Common for testing normality\n"
            ]
        },
        
        # Cell 11: Advanced Visualizations
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Generate sample data\n",
                "np.random.seed(90)\n",
                "sample_data = np.random.normal(100, 20, 500)\n",
                "\n",
                "# Create comprehensive visualization\n",
                "fig = plt.figure(figsize=(15, 10))\n",
                "gs = fig.add_gridspec(3, 3, hspace=0.3, wspace=0.3)\n",
                "\n",
                "# 1. Histogram\n",
                "ax1 = fig.add_subplot(gs[0, 0])\n",
                "ax1.hist(sample_data, bins=25, edgecolor='black', color='skyblue', alpha=0.7)\n",
                "ax1.set_title('Histogram', fontweight='bold')\n",
                "ax1.set_xlabel('Value')\n",
                "ax1.set_ylabel('Frequency')\n",
                "ax1.grid(axis='y', alpha=0.3)\n",
                "\n",
                "# 2. Density Plot (KDE)\n",
                "ax2 = fig.add_subplot(gs[0, 1])\n",
                "from scipy.stats import gaussian_kde\n",
                "kde = gaussian_kde(sample_data)\n",
                "x_range = np.linspace(sample_data.min(), sample_data.max(), 200)\n",
                "ax2.plot(x_range, kde(x_range), linewidth=2, color='darkgreen')\n",
                "ax2.fill_between(x_range, kde(x_range), alpha=0.3, color='green')\n",
                "ax2.set_title('Density Plot (KDE)', fontweight='bold')\n",
                "ax2.set_xlabel('Value')\n",
                "ax2.set_ylabel('Density')\n",
                "ax2.grid(alpha=0.3)\n",
                "\n",
                "# 3. Box Plot\n",
                "ax3 = fig.add_subplot(gs[0, 2])\n",
                "ax3.boxplot(sample_data, vert=True, patch_artist=True,\n",
                "           boxprops=dict(facecolor='lightcoral'),\n",
                "           medianprops=dict(color='darkred', linewidth=2))\n",
                "ax3.set_title('Box Plot', fontweight='bold')\n",
                "ax3.set_ylabel('Value')\n",
                "ax3.grid(axis='y', alpha=0.3)\n",
                "\n",
                "# 4. Violin Plot\n",
                "ax4 = fig.add_subplot(gs[1, 0])\n",
                "parts = ax4.violinplot([sample_data], positions=[1], showmeans=True, showmedians=True)\n",
                "for pc in parts['bodies']:\n",
                "    pc.set_facecolor('plum')\n",
                "    pc.set_alpha(0.7)\n",
                "ax4.set_title('Violin Plot', fontweight='bold')\n",
                "ax4.set_ylabel('Value')\n",
                "ax4.grid(axis='y', alpha=0.3)\n",
                "\n",
                "# 5. CDF (Cumulative Distribution)\n",
                "ax5 = fig.add_subplot(gs[1, 1])\n",
                "sorted_data = np.sort(sample_data)\n",
                "cdf = np.arange(1, len(sorted_data) + 1) / len(sorted_data)\n",
                "ax5.plot(sorted_data, cdf, linewidth=2, color='navy')\n",
                "ax5.set_title('Cumulative Distribution', fontweight='bold')\n",
                "ax5.set_xlabel('Value')\n",
                "ax5.set_ylabel('Cumulative Probability')\n",
                "ax5.grid(alpha=0.3)\n",
                "\n",
                "# 6. Q-Q Plot\n",
                "ax6 = fig.add_subplot(gs[1, 2])\n",
                "stats.probplot(sample_data, dist=\"norm\", plot=ax6)\n",
                "ax6.set_title('Q-Q Plot (Normality Test)', fontweight='bold')\n",
                "ax6.grid(alpha=0.3)\n",
                "\n",
                "# 7. Combined Histogram + KDE\n",
                "ax7 = fig.add_subplot(gs[2, :])\n",
                "ax7.hist(sample_data, bins=30, density=True, edgecolor='black', color='lightblue', alpha=0.6, label='Histogram')\n",
                "ax7.plot(x_range, kde(x_range), linewidth=2, color='red', label='KDE')\n",
                "ax7.axvline(sample_data.mean(), color='green', linestyle='--', linewidth=2, label=f'Mean: {sample_data.mean():.1f}')\n",
                "ax7.axvline(np.median(sample_data), color='orange', linestyle=':', linewidth=2, label=f'Median: {np.median(sample_data):.1f}')\n",
                "ax7.set_title('Combined: Histogram + Density + Central Tendency', fontsize=13, fontweight='bold')\n",
                "ax7.set_xlabel('Value')\n",
                "ax7.set_ylabel('Density')\n",
                "ax7.legend()\n",
                "ax7.grid(axis='y', alpha=0.3)\n",
                "\n",
                "plt.suptitle('Comprehensive Numerical Data Visualization Suite', fontsize=15, fontweight='bold', y=0.995)\n",
                "plt.show()\n",
                "\n",
                "print(f'Sample Statistics:')\n",
                "print(f'  Mean: {sample_data.mean():.2f}')\n",
                "print(f'  Median: {np.median(sample_data):.2f}')\n",
                "print(f'  Std Dev: {sample_data.std():.2f}')\n",
                "print(f'  Skewness: {stats.skew(sample_data):.2f}')\n",
                "print(f'  Kurtosis: {stats.kurtosis(sample_data):.2f}')"
            ]
        },
        
        # Cell 12: Real-World Application
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 5. Real-World Application: Customer Analytics\n",
                "\n",
                "### Business Scenario\n",
                "A retail company wants to analyze customer spending patterns to:\n",
                "- Understand typical purchase amounts\n",
                "- Identify high-value customers (outliers)\n",
                "- Compare spending across customer segments\n",
                "- Optimize pricing and promotions\n",
                "\n",
                "### Analysis Goals\n",
                "1. Distribution of purchase amounts\n",
                "2. Detect unusual spending patterns\n",
                "3. Compare different customer segments\n",
                "4. Identify actionable insights\n"
            ]
        },
        
        # Cell 13: Customer Analytics Implementation
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Generate realistic customer purchase data\n",
                "np.random.seed(200)\n",
                "\n",
                "# Three customer segments\n",
                "budget_customers = np.random.gamma(shape=2, scale=15, size=500)\n",
                "regular_customers = np.random.gamma(shape=3, scale=25, size=800)\n",
                "premium_customers = np.random.gamma(shape=5, scale=40, size=200)\n",
                "\n",
                "# Combine all purchases\n",
                "all_purchases = np.concatenate([budget_customers, regular_customers, premium_customers])\n",
                "\n",
                "# Create DataFrame\n",
                "segments = ['Budget']*500 + ['Regular']*800 + ['Premium']*200\n",
                "purchase_df = pd.DataFrame({\n",
                "    'Purchase_Amount': all_purchases,\n",
                "    'Segment': segments\n",
                "})\n",
                "\n",
                "# Analysis Dashboard\n",
                "print('CUSTOMER PURCHASE ANALYTICS')\n",
                "print('='*70)\n",
                "\n",
                "# Overall statistics\n",
                "print('\\n1. Overall Purchase Statistics:')\n",
                "print(f'   Total transactions: {len(all_purchases):,}')\n",
                "print(f'   Average purchase: ${all_purchases.mean():.2f}')\n",
                "print(f'   Median purchase: ${np.median(all_purchases):.2f}')\n",
                "print(f'   Std deviation: ${all_purchases.std():.2f}')\n",
                "print(f'   Skewness: {stats.skew(all_purchases):.2f} (right-skewed)')\n",
                "\n",
                "# Segment comparison\n",
                "print('\\n2. Segment Analysis:')\n",
                "for segment in ['Budget', 'Regular', 'Premium']:\n",
                "    seg_data = purchase_df[purchase_df['Segment'] == segment]['Purchase_Amount']\n",
                "    print(f'   {segment:8s}: Mean=${seg_data.mean():6.2f}, Median=${seg_data.median():6.2f}, n={len(seg_data):4d}')\n",
                "\n",
                "# Outlier detection\n",
                "q1 = np.percentile(all_purchases, 25)\n",
                "q3 = np.percentile(all_purchases, 75)\n",
                "iqr = q3 - q1\n",
                "upper_fence = q3 + 1.5 * iqr\n",
                "high_value_customers = all_purchases[all_purchases > upper_fence]\n",
                "\n",
                "print(f'\\n3. High-Value Customer Detection:')\n",
                "print(f'   Upper outlier threshold: ${upper_fence:.2f}')\n",
                "print(f'   High-value transactions: {len(high_value_customers)} ({len(high_value_customers)/len(all_purchases)*100:.1f}%)')\n",
                "print(f'   Average high-value purchase: ${high_value_customers.mean():.2f}')\n",
                "\n",
                "# Visualization\n",
                "fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n",
                "\n",
                "# Overall distribution\n",
                "axes[0, 0].hist(all_purchases, bins=40, edgecolor='black', color='steelblue', alpha=0.7)\n",
                "axes[0, 0].axvline(all_purchases.mean(), color='red', linestyle='--', linewidth=2, label=f'Mean: ${all_purchases.mean():.0f}')\n",
                "axes[0, 0].axvline(np.median(all_purchases), color='green', linestyle=':', linewidth=2, label=f'Median: ${np.median(all_purchases):.0f}')\n",
                "axes[0, 0].set_title('All Customers: Purchase Distribution', fontweight='bold')\n",
                "axes[0, 0].set_xlabel('Purchase Amount ($)')\n",
                "axes[0, 0].set_ylabel('Frequency')\n",
                "axes[0, 0].legend()\n",
                "axes[0, 0].grid(axis='y', alpha=0.3)\n",
                "\n",
                "# Box plot by segment\n",
                "purchase_df.boxplot(column='Purchase_Amount', by='Segment', ax=axes[0, 1])\n",
                "axes[0, 1].set_title('Segment Comparison: Box Plots', fontweight='bold')\n",
                "axes[0, 1].set_xlabel('Customer Segment')\n",
                "axes[0, 1].set_ylabel('Purchase Amount ($)')\n",
                "axes[0, 1].get_figure().suptitle('')  # Remove default title\n",
                "\n",
                "# Density plots by segment\n",
                "for segment, color in zip(['Budget', 'Regular', 'Premium'], ['red', 'blue', 'green']):\n",
                "    seg_data = purchase_df[purchase_df['Segment'] == segment]['Purchase_Amount']\n",
                "    seg_data.plot(kind='density', ax=axes[1, 0], label=segment, color=color, linewidth=2)\n",
                "\n",
                "axes[1, 0].set_title('Segment Comparison: Density Plots', fontweight='bold')\n",
                "axes[1, 0].set_xlabel('Purchase Amount ($)')\n",
                "axes[1, 0].set_ylabel('Density')\n",
                "axes[1, 0].legend()\n",
                "axes[1, 0].grid(alpha=0.3)\n",
                "\n",
                "# CDF\n",
                "sorted_purchases = np.sort(all_purchases)\n",
                "cdf = np.arange(1, len(sorted_purchases) + 1) / len(sorted_purchases)\n",
                "axes[1, 1].plot(sorted_purchases, cdf * 100, linewidth=2, color='purple')\n",
                "axes[1, 1].axhline(50, color='red', linestyle='--', alpha=0.5, label='50th percentile')\n",
                "axes[1, 1].axhline(75, color='orange', linestyle='--', alpha=0.5, label='75th percentile')\n",
                "axes[1, 1].axhline(90, color='green', linestyle='--', alpha=0.5, label='90th percentile')\n",
                "axes[1, 1].set_title('Cumulative Distribution', fontweight='bold')\n",
                "axes[1, 1].set_xlabel('Purchase Amount ($)')\n",
                "axes[1, 1].set_ylabel('Cumulative Percentage (%)')\n",
                "axes[1, 1].legend()\n",
                "axes[1, 1].grid(alpha=0.3)\n",
                "\n",
                "plt.tight_layout()\n",
                "plt.show()\n",
                "\n",
                "# Business insights\n",
                "print('\\n4. Business Insights:')\n",
                "print('   ✓ Right-skewed distribution indicates most purchases are low-to-moderate')\n",
                "print('   ✓ Premium segment drives higher average transaction value')\n",
                "print('   ✓ High-value outliers represent VIP customer opportunities')\n",
                "print('   ✓ Consider targeted promotions for budget customers to increase spend')"
            ]
        },
        
        # Cell 14: Summary
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Summary & Key Takeaways\n",
                "\n",
                "### Core Visualization Techniques\n",
                "\n",
                "1. **Histograms**\n",
                "   - Best for showing frequency distribution of continuous data\n",
                "   - Choose bin count carefully (Sturges, Square Root, Rice rules)\n",
                "   - Adjacent bars (no gaps) distinguish from bar charts\n",
                "\n",
                "2. **Distribution Shapes**\n",
                "   - **Symmetric**: Mean ≈ Median, balanced distribution\n",
                "   - **Right-skewed**: Mean > Median, tail to right\n",
                "   - **Left-skewed**: Mean < Median, tail to left\n",
                "   - Use skewness statistic to quantify asymmetry\n",
                "\n",
                "3. **Box Plots**\n",
                "   - Compact five-number summary visualization\n",
                "   - Excellent for outlier detection\n",
                "   - Perfect for comparing multiple groups\n",
                "   - IQR method identifies potential outliers\n",
                "\n",
                "4. **Advanced Techniques**\n",
                "   - **Density plots (KDE)**: Smooth distribution curves\n",
                "   - **Violin plots**: Combine box plot with density\n",
                "   - **CDF**: Cumulative probability view\n",
                "   - **Q-Q plots**: Test for normality\n",
                "\n",
                "### Choosing the Right Visualization\n",
                "\n",
                "| Goal | Best Choice |\n",
                "|------|-------------|\n",
                "| Show distribution shape | Histogram or density plot |\n",
                "| Compare groups | Box plots or violin plots |\n",
                "| Identify outliers | Box plot |\n",
                "| Show cumulative probability | CDF |\n",
                "| Test normality | Q-Q plot + histogram |\n",
                "| Precise frequencies | Histogram with counts |\n",
                "\n",
                "### Practical Applications\n",
                "- Customer behavior analysis\n",
                "- Quality control (process monitoring)\n",
                "- Financial data analysis\n",
                "- Healthcare metrics\n",
                "- Performance benchmarking\n",
                "\n",
                "### Next Steps\n",
                "- Week 4: Central tendency measures (mean, median, mode calculations)\n",
                "- Week 5: Dispersion measures (variance, standard deviation, IQR)\n",
                "- Week 6: Correlation and association between variables\n"
            ]
        }
    ]
    
    notebook['cells'] = cells
    return notebook

# Generate and save notebook
if __name__ == '__main__':
    notebook = create_week3_notebook()
    output_path = '../01-Foundation-Level/02-Statistics-I/notebooks/week-03-numerical-data-visualization.ipynb'
    
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(notebook, f, indent=2, ensure_ascii=False)
    
    print(f'✓ Week 3 enhanced: {len(notebook["cells"])} cells')

