/* FOUNDATION 44 — Corpus: Statistics for Data Science I
   Source clauses S1.01 … S1.07 of the Foundation Theory Handbook. */
window.CORPUS = (window.CORPUS || []).concat([

/* ── S1.01 Data types and scales ─ yield 1 ─────────────────────────── */
{ id:'S1.01.dsc01', clause:'S1.01', course:'S1', yield:1, type:'DISCRIM',
  left:'Parameter', right:'Statistic',
  items:[{t:'Describes the population', side:'L'},{t:'Computed from the sample', side:'R'},
         {t:'μ, σ, p', side:'L'},{t:'x̄, s, p̂', side:'R'},
         {t:'Fixed but usually unknown', side:'L'},{t:'Random — varies sample to sample', side:'R'}] },
{ id:'S1.01.c01', clause:'S1.01', course:'S1', yield:1, type:'CLASSIFY',
  prompt:'Temperature in °C sits on which scale?',
  options:['Interval','Ratio','Ordinal','Nominal'], answer:0 },
{ id:'S1.01.c02', clause:'S1.01', course:'S1', yield:1, type:'CLASSIFY',
  prompt:'Jersey numbers on players are which type of variable?',
  options:['Nominal','Ordinal','Interval','Ratio'], answer:0 },
{ id:'S1.01.c03', clause:'S1.01', course:'S1', yield:1, type:'CLASSIFY',
  prompt:'Satisfaction rating (poor / fair / good) is…',
  options:['Ordinal','Nominal','Interval','Ratio'], answer:0 },
{ id:'S1.01.c04', clause:'S1.01', course:'S1', yield:1, type:'CLASSIFY',
  prompt:'Which scale is the first to permit a meaningful mean and SD?',
  options:['Interval','Nominal','Ordinal','Ratio'], answer:0 },
{ id:'S1.01.c05', clause:'S1.01', course:'S1', yield:1, type:'CLASSIFY',
  prompt:'The only measure of centre available for nominal data is the…',
  options:['mode','median','mean','midrange'], answer:0 },
{ id:'S1.01.t01', clause:'S1.01', course:'S1', yield:1, type:'TRAP',
  claim:'20 °C is twice as hot as 10 °C.', verdict:false, because:'nozero',
  reasons:[{k:'nozero',label:'°C is interval — its zero is arbitrary, so ratios are meaningless'},{k:'rounding',label:'the values are only approximate'},{k:'ordinal',label:'temperature is ordinal'},{k:'true',label:'the statement is correct'}] },
{ id:'S1.01.co01', clause:'S1.01', course:'S1', yield:1, type:'CONDITION',
  prompt:'Report the mean of a set of pin codes.', verdict:'reject', because:'nominal',
  reasons:[{k:'nominal',label:'pin codes are nominal labels — averaging them is meaningless'},{k:'toolarge',label:'the numbers are too large'},{k:'skewed',label:'the distribution is skewed'},{k:'ok',label:'nothing is wrong'}] },

/* ── S1.02 Categorical data ─ yield 1 ──────────────────────────────── */
{ id:'S1.02.f01', clause:'S1.02', course:'S1', yield:1, type:'FORMULA',
  prompt:'Pie chart: angle for category i with frequency fᵢ out of n',
  answer:'360*f_i/n', accept:['360 fi / n','(fi/n)*360'] },
{ id:'S1.02.c01', clause:'S1.02', course:'S1', yield:1, type:'CLASSIFY',
  prompt:'A Pareto chart is a bar chart that is…',
  options:['sorted descending with a cumulative-% line','sorted ascending','circular','three-dimensional'], answer:0 },
{ id:'S1.02.c02', clause:'S1.02', course:'S1', yield:1, type:'CLASSIFY',
  prompt:'Relative frequencies across all categories always sum to…',
  options:['1','100','n','0'], answer:0 },
{ id:'S1.02.t01', clause:'S1.02', course:'S1', yield:1, type:'TRAP',
  claim:'Starting a bar chart’s y-axis above zero is a neutral presentation choice.', verdict:false, because:'truncated',
  reasons:[{k:'truncated',label:'a truncated axis exaggerates differences'},{k:'fine',label:'it saves space and is harmless'},{k:'required',label:'axes must never start at zero'},{k:'area',label:'it distorts area, not length'}] },
{ id:'S1.02.t02', clause:'S1.02', course:'S1', yield:1, type:'TRAP',
  claim:'Scaling an icon’s width and height by k makes it look k times bigger.', verdict:false, because:'ksq',
  reasons:[{k:'ksq',label:'perceived size scales by k², not k'},{k:'klin',label:'perceived size scales linearly'},{k:'kcube',label:'perceived size scales by k³'},{k:'true',label:'the statement is correct'}] },
{ id:'S1.02.dsc01', clause:'S1.02', course:'S1', yield:1, type:'DISCRIM',
  left:'Bar chart', right:'Histogram',
  items:[{t:'Bars are separated', side:'L'},{t:'Bars are adjacent', side:'R'},
         {t:'For categorical data', side:'L'},{t:'For numerical data in bins', side:'R'},
         {t:'Height = frequency', side:'L'},{t:'Area ∝ frequency', side:'R'}] },

/* ── S1.03 Numerical data ─ yield 3 ────────────────────────────────── */
{ id:'S1.03.f01', clause:'S1.03', course:'S1', yield:3, type:'FORMULA',
  prompt:'Sample mean x̄ for raw data', answer:'(1/n)sum x_i', accept:['sum(xi)/n','Σx/n'] },
{ id:'S1.03.f02', clause:'S1.03', course:'S1', yield:3, type:'FORMULA',
  prompt:'Grouped-data mean using class marks mᵢ and frequencies fᵢ',
  answer:'sum(f_i m_i)/sum(f_i)', accept:['Σfm/Σf'] },
{ id:'S1.03.f03', clause:'S1.03', course:'S1', yield:3, type:'FORMULA',
  prompt:'Population variance σ² (divisor N)', answer:'(1/N)sum(x_i-mu)^2', accept:['Σ(x−μ)²/N'] },
{ id:'S1.03.f04', clause:'S1.03', course:'S1', yield:3, type:'FORMULA',
  prompt:'Sample variance s² (divisor n − 1)', answer:'(1/(n-1))sum(x_i-xbar)^2', accept:['Σ(x−x̄)²/(n−1)'] },
{ id:'S1.03.f05', clause:'S1.03', course:'S1', yield:3, type:'FORMULA',
  prompt:'Computational form of the sample variance',
  answer:'(sum x_i^2-n xbar^2)/(n-1)', accept:['(Σx² − n x̄²)/(n−1)'] },
{ id:'S1.03.f06', clause:'S1.03', course:'S1', yield:3, type:'FORMULA',
  prompt:'Coefficient of variation', answer:'(s/xbar)*100%', accept:['s/x̄ × 100','100 s / xbar'] },
{ id:'S1.03.f07', clause:'S1.03', course:'S1', yield:3, type:'FORMULA',
  prompt:'The 1.5·IQR outlier fences', answer:'Q1-1.5*IQR and Q3+1.5*IQR', accept:['below Q1−1.5IQR or above Q3+1.5IQR'] },
{ id:'S1.03.f08', clause:'S1.03', course:'S1', yield:3, type:'FORMULA',
  prompt:'Under y = a + bx, give ȳ, s_y and IQR_y',
  answer:'ybar=a+b xbar, s_y=|b| s_x, IQR_y=|b| IQR_x', accept:['a+b x̄; |b|s; |b|IQR'] },
{ id:'S1.03.c01', clause:'S1.03', course:'S1', yield:3, type:'CLASSIFY',
  prompt:'Right-skewed data orders the centres how?',
  options:['mode < median < mean','mean < median < mode','all equal','median < mode < mean'], answer:0 },
{ id:'S1.03.c02', clause:'S1.03', course:'S1', yield:3, type:'CLASSIFY',
  prompt:'Which measure of centre minimises Σ(xᵢ − c)²?',
  options:['the mean','the median','the mode','the midrange'], answer:0 },
{ id:'S1.03.c03', clause:'S1.03', course:'S1', yield:3, type:'CLASSIFY',
  prompt:'Which measure of centre minimises Σ|xᵢ − c|?',
  options:['the median','the mean','the mode','Q₁'], answer:0 },
{ id:'S1.03.c04', clause:'S1.03', course:'S1', yield:3, type:'CLASSIFY',
  prompt:'Boxplot whiskers extend to…',
  options:['the most extreme points inside the fences','the fences themselves','min and max always','±2 SD'], answer:0 },
{ id:'S1.03.dsc01', clause:'S1.03', course:'S1', yield:3, type:'DISCRIM',
  left:'Mean', right:'Median',
  items:[{t:'Minimises Σ(x − c)²', side:'L'},{t:'Minimises Σ|x − c|', side:'R'},
         {t:'Sensitive to outliers', side:'L'},{t:'Resistant to outliers', side:'R'},
         {t:'Uses every value', side:'L'},{t:'Uses only the middle position', side:'R'},
         {t:'Σ(xᵢ − this) = 0', side:'L'},{t:'Available for ordinal data', side:'R'}] },
{ id:'S1.03.dsc02', clause:'S1.03', course:'S1', yield:3, type:'DISCRIM',
  left:'Divisor n', right:'Divisor n − 1',
  items:[{t:'Population variance σ²', side:'L'},{t:'Sample variance s²', side:'R'},
         {t:'Biased downward as an estimator of σ²', side:'L'},{t:'Unbiased estimator of σ²', side:'R'},
         {t:'Used when μ is known', side:'L'},{t:'Costs one degree of freedom for x̄', side:'R'}] },
{ id:'S1.03.d01', clause:'S1.03', course:'S1', yield:3, type:'DERIVE',
  prompt:'Why divide by n − 1 in the sample variance?',
  answer:'xbar is estimated from the same data, costing one degree of freedom; it makes s^2 unbiased',
  accept:['one df is spent estimating the mean, making s² unbiased for σ²'] },
{ id:'S1.03.t01', clause:'S1.03', course:'S1', yield:3, type:'TRAP',
  claim:'Adding a constant to every value changes the standard deviation.', verdict:false, because:'shift',
  reasons:[{k:'shift',label:'shifting changes location only; spread is unchanged'},{k:'scales',label:'it scales the SD by the constant'},{k:'squares',label:'it squares the SD'},{k:'true',label:'the SD does change'}] },

/* ── S1.04 Association ─ yield 3 ───────────────────────────────────── */
{ id:'S1.04.f01', clause:'S1.04', course:'S1', yield:3, type:'FORMULA',
  prompt:'Sample covariance of x and y',
  answer:'(1/(n-1))sum(x_i-xbar)(y_i-ybar)', accept:['(Σxy − n x̄ȳ)/(n−1)'] },
{ id:'S1.04.f02', clause:'S1.04', course:'S1', yield:3, type:'FORMULA',
  prompt:'Correlation r in terms of covariance and the two SDs',
  answer:'cov(x,y)/(s_x s_y)', accept:['cov/(sx*sy)'] },
{ id:'S1.04.f03', clause:'S1.04', course:'S1', yield:3, type:'FORMULA',
  prompt:'Least-squares slope b₁ in terms of r, s_y and s_x',
  answer:'b1=r*s_y/s_x', accept:['r sy/sx','cov(x,y)/s_x^2'] },
{ id:'S1.04.f04', clause:'S1.04', course:'S1', yield:3, type:'FORMULA',
  prompt:'Least-squares intercept b₀', answer:'b0=ybar-b1*xbar', accept:['ȳ − b₁x̄'] },
{ id:'S1.04.f05', clause:'S1.04', course:'S1', yield:3, type:'FORMULA',
  prompt:'Definition of the residual eᵢ', answer:'e_i=y_i-yhat_i', accept:['observed minus fitted'] },
{ id:'S1.04.c01', clause:'S1.04', course:'S1', yield:3, type:'CLASSIFY',
  prompt:'The four things to read off a scatterplot are…',
  options:['direction, form, strength, outliers','mean, median, mode, range','slope, intercept, r, r²','centre, spread, shape, gaps'], answer:0 },
{ id:'S1.04.c02', clause:'S1.04', course:'S1', yield:3, type:'CLASSIFY',
  prompt:'r² is interpreted as…',
  options:['the proportion of variation in y explained by the linear relation with x','the slope of the line','the correlation','the residual sum of squares'], answer:0 },
{ id:'S1.04.c03', clause:'S1.04', course:'S1', yield:3, type:'CLASSIFY',
  prompt:'Under x′ = a + bx with b < 0, the correlation r…',
  options:['flips sign','is unchanged','becomes zero','scales by b'], answer:0 },
{ id:'S1.04.dsc01', clause:'S1.04', course:'S1', yield:3, type:'DISCRIM',
  left:'Covariance', right:'Correlation r',
  items:[{t:'Units of x × units of y', side:'L'},{t:'Unitless', side:'R'},
         {t:'Range (−∞, ∞)', side:'L'},{t:'Range [−1, 1]', side:'R'},
         {t:'Magnitude means nothing comparable', side:'L'},{t:'Magnitude means strength of linear relation', side:'R'},
         {t:'Scales by b under x′ = a + bx', side:'L'},{t:'Unchanged if b > 0', side:'R'}] },
{ id:'S1.04.t01', clause:'S1.04', course:'S1', yield:3, type:'TRAP',
  claim:'r = 0 means x and y have no relationship.', verdict:false, because:'linear',
  reasons:[{k:'linear',label:'r measures linear association only — a perfect parabola gives r = 0'},{k:'sample',label:'the sample was too small'},{k:'causal',label:'it means no causal relationship only'},{k:'true',label:'the statement is correct'}] },
{ id:'S1.04.t02', clause:'S1.04', course:'S1', yield:3, type:'TRAP',
  claim:'r is symmetric in x and y, and so is the regression slope.', verdict:false, because:'slopeasym',
  reasons:[{k:'slopeasym',label:'r is symmetric but the regression slope is not'},{k:'bothsym',label:'both are symmetric'},{k:'neithersym',label:'neither is symmetric'},{k:'rasym',label:'r is the asymmetric one'}] },
{ id:'S1.04.co01', clause:'S1.04', course:'S1', yield:3, type:'CONDITION',
  prompt:'Use the fitted line to predict y at an x far outside the observed range.',
  verdict:'reject', because:'extrap',
  reasons:[{k:'extrap',label:'extrapolation outside the observed range of x is unjustified'},{k:'rlow',label:'r is too low'},{k:'resid',label:'the residuals are not normal'},{k:'ok',label:'nothing is wrong'}] },
{ id:'S1.04.co02', clause:'S1.04', course:'S1', yield:3, type:'CONDITION',
  prompt:'A strong correlation is reported, so the paper concludes x causes y.',
  verdict:'reject', because:'causation',
  reasons:[{k:'causation',label:'correlation is not causation — confounding and lurking variables'},{k:'rsq',label:'r² was not reported'},{k:'nlarge',label:'n was too large'},{k:'ok',label:'nothing is wrong'}] },
{ id:'S1.04.c04', clause:'S1.04', course:'S1', yield:3, type:'CLASSIFY',
  prompt:'Two categorical variables look independent when…',
  options:['every conditional distribution matches the marginal','the table is square','all counts are equal','the totals match'], answer:0 },

/* ── S1.05 Permutations and combinations ─ yield 3 ─────────────────── */
{ id:'S1.05.f01', clause:'S1.05', course:'S1', yield:3, type:'FORMULA',
  prompt:'Permutations of r from n distinct objects, ⁿPᵣ',
  answer:'n!/(n-r)!', accept:['P(n,r)=n!/(n−r)!'] },
{ id:'S1.05.f02', clause:'S1.05', course:'S1', yield:3, type:'FORMULA',
  prompt:'Combinations of r from n distinct objects, ⁿCᵣ',
  answer:'n!/(r!(n-r)!)', accept:['C(n,r)','binom(n,r)'] },
{ id:'S1.05.f03', clause:'S1.05', course:'S1', yield:3, type:'FORMULA',
  prompt:'Arrangements of n objects with repeats n₁, n₂, …, n_k',
  answer:'n!/(n1! n2! ... nk!)', accept:['n! / product of ni!'] },
{ id:'S1.05.f04', clause:'S1.05', course:'S1', yield:3, type:'FORMULA',
  prompt:'r selections from n types, repetition allowed, order does NOT matter',
  answer:'C(n+r-1,r)', accept:['binom(n+r−1, r)'] },
{ id:'S1.05.f05', clause:'S1.05', course:'S1', yield:3, type:'FORMULA',
  prompt:'r selections from n types, repetition allowed, order MATTERS',
  answer:'n^r', accept:['n**r'] },
{ id:'S1.05.f06', clause:'S1.05', course:'S1', yield:3, type:'FORMULA',
  prompt:'Circular arrangements of n distinct objects',
  answer:'(n-1)!', accept:['(n−1)! , or (n−1)!/2 if reflections identified'] },
{ id:'S1.05.f07', clause:'S1.05', course:'S1', yield:3, type:'FORMULA',
  prompt:'Pascal’s identity: C(n,r) + C(n,r−1) = ?', answer:'C(n+1,r)', accept:['binom(n+1,r)'] },
{ id:'S1.05.f08', clause:'S1.05', course:'S1', yield:3, type:'FORMULA',
  prompt:'Sum of all binomial coefficients Σ C(n,r) for r = 0…n',
  answer:'2^n', accept:['2**n'] },
{ id:'S1.05.f09', clause:'S1.05', course:'S1', yield:3, type:'FORMULA',
  prompt:'Binomial theorem: (a + b)ⁿ = ?',
  answer:'sum_{r=0}^{n} C(n,r) a^(n-r) b^r', accept:['Σ nCr a^(n−r) b^r'] },
{ id:'S1.05.f10', clause:'S1.05', course:'S1', yield:3, type:'FORMULA',
  prompt:'The (r+1)-th term of the binomial expansion of (a + b)ⁿ',
  answer:'C(n,r) a^(n-r) b^r', accept:['nCr a^(n−r) b^r'] },
{ id:'S1.05.dsc01', clause:'S1.05', course:'S1', yield:3, type:'DISCRIM',
  left:'Permutation', right:'Combination',
  items:[{t:'Order matters', side:'L'},{t:'Order does not matter', side:'R'},
         {t:'n!/(n−r)!', side:'L'},{t:'n!/(r!(n−r)!)', side:'R'},
         {t:'Swapping two chosen items gives a new outcome', side:'L'},{t:'Swapping two chosen items gives the same outcome', side:'R'},
         {t:'Arranging books on a shelf', side:'L'},{t:'Choosing a committee', side:'R'}] },
{ id:'S1.05.ch01', clause:'S1.05', course:'S1', yield:3, type:'CHAIN',
  prompt:'Counting arrangements where certain items must stay together — order the method',
  steps:['Glue the joined items into a single block','Arrange the blocks together with the remaining items','Arrange the items within the block','Multiply the two counts'] },
{ id:'S1.05.t01', clause:'S1.05', course:'S1', yield:3, type:'TRAP',
  claim:'“At least one” problems are usually easiest computed directly.', verdict:false, because:'complement',
  reasons:[{k:'complement',label:'use 1 − P(none) — the complement is almost always easier'},{k:'direct',label:'direct enumeration is always fastest'},{k:'perm',label:'they always reduce to permutations'},{k:'true',label:'the statement is correct'}] },
{ id:'S1.05.c01', clause:'S1.05', course:'S1', yield:3, type:'CLASSIFY',
  prompt:'Items that must be SEPARATED are handled by…',
  options:['arranging the others first, then placing into the gaps','gluing them into a block','dividing by 2','using combinations'], answer:0 },

/* ── S1.06 Probability ─ yield 2 ───────────────────────────────────── */
{ id:'S1.06.f01', clause:'S1.06', course:'S1', yield:2, type:'FORMULA',
  prompt:'Kolmogorov’s three axioms, stated compactly',
  answer:'P(A)>=0; P(S)=1; countable additivity for disjoint events',
  accept:['nonnegative, total one, additive over disjoint unions'] },
{ id:'S1.06.f02', clause:'S1.06', course:'S1', yield:2, type:'FORMULA',
  prompt:'Complement rule: P(Aᶜ) = ?', answer:'1-P(A)', accept:['1 − P(A)'] },
{ id:'S1.06.f03', clause:'S1.06', course:'S1', yield:2, type:'FORMULA',
  prompt:'Addition rule for two events', answer:'P(A)+P(B)-P(A∩B)', accept:['P(A)+P(B)−P(A and B)'] },
{ id:'S1.06.f04', clause:'S1.06', course:'S1', yield:2, type:'FORMULA',
  prompt:'P(A \\ B) in terms of P(A) and P(A ∩ B)', answer:'P(A)-P(A∩B)', accept:['P(A) − P(A and B)'] },
{ id:'S1.06.f05', clause:'S1.06', course:'S1', yield:2, type:'FORMULA',
  prompt:'Boole’s inequality', answer:'P(union A_i)<=sum P(A_i)', accept:['P(∪Aᵢ) ≤ ΣP(Aᵢ)'] },
{ id:'S1.06.f06', clause:'S1.06', course:'S1', yield:2, type:'FORMULA',
  prompt:'Equally likely outcomes: P(A) = ?', answer:'|A|/|S|', accept:['favourable/total'] },
{ id:'S1.06.t01', clause:'S1.06', course:'S1', yield:2, type:'TRAP',
  claim:'Mutually exclusive events with positive probability are independent.', verdict:false, because:'dependent',
  reasons:[{k:'dependent',label:'they are necessarily dependent — knowing A occurred tells you B did not'},{k:'indep',label:'disjointness is exactly independence'},{k:'needs3',label:'it holds only for three or more events'},{k:'true',label:'the statement is correct'}] },
{ id:'S1.06.t02', clause:'S1.06', course:'S1', yield:2, type:'TRAP',
  claim:'For the sum of two dice, the outcomes {2,…,12} are equally likely.', verdict:false, because:'notsym',
  reasons:[{k:'notsym',label:'the sample space is not symmetric — the 36 ordered pairs are'},{k:'sym',label:'the sums are symmetric so they are equally likely'},{k:'depends',label:'it depends on the dice'},{k:'true',label:'the statement is correct'}] },
{ id:'S1.06.dsc01', clause:'S1.06', course:'S1', yield:2, type:'DISCRIM',
  left:'Mutually exclusive', right:'Independent',
  items:[{t:'A ∩ B = ∅', side:'L'},{t:'P(A ∩ B) = P(A)P(B)', side:'R'},
         {t:'Cannot both occur', side:'L'},{t:'Occurrence of one says nothing about the other', side:'R'},
         {t:'P(A ∪ B) = P(A) + P(B)', side:'L'},{t:'P(A | B) = P(A)', side:'R'}] },

/* ── S1.07 Conditional probability, independence, Bayes ─ yield 3 ──── */
{ id:'S1.07.f01', clause:'S1.07', course:'S1', yield:3, type:'FORMULA',
  prompt:'Definition of conditional probability P(A | B)',
  answer:'P(A∩B)/P(B)', accept:['P(A and B)/P(B)'] },
{ id:'S1.07.f02', clause:'S1.07', course:'S1', yield:3, type:'FORMULA',
  prompt:'Multiplication rule for P(A ∩ B), both orderings',
  answer:'P(B)P(A|B)=P(A)P(B|A)', accept:['P(A)P(B|A)'] },
{ id:'S1.07.f03', clause:'S1.07', course:'S1', yield:3, type:'FORMULA',
  prompt:'Chain rule for P(A₁ ∩ … ∩ Aₙ)',
  answer:'P(A1)P(A2|A1)...P(An|A1∩...∩A_{n-1})', accept:['product of successive conditionals'] },
{ id:'S1.07.f04', clause:'S1.07', course:'S1', yield:3, type:'FORMULA',
  prompt:'Independence of A and B, stated two ways',
  answer:'P(A∩B)=P(A)P(B); equivalently P(A|B)=P(A)', accept:['product rule, or conditional equals marginal'] },
{ id:'S1.07.f05', clause:'S1.07', course:'S1', yield:3, type:'FORMULA',
  prompt:'Law of total probability over a partition B₁…B_k',
  answer:'P(A)=sum P(B_i)P(A|B_i)', accept:['ΣP(Bᵢ)P(A|Bᵢ)'] },
{ id:'S1.07.f06', clause:'S1.07', course:'S1', yield:3, type:'FORMULA',
  prompt:'Bayes’ rule for P(B_j | A)',
  answer:'P(B_j)P(A|B_j)/sum_i P(B_i)P(A|B_i)', accept:['prior×likelihood / total probability'] },
{ id:'S1.07.c01', clause:'S1.07', course:'S1', yield:3, type:'CLASSIFY',
  prompt:'In Bayes’ rule, P(A | B_j) is called the…',
  options:['likelihood','prior','posterior','evidence'], answer:0 },
{ id:'S1.07.c02', clause:'S1.07', course:'S1', yield:3, type:'CLASSIFY',
  prompt:'If A and B are independent, which pair is NOT guaranteed independent?',
  options:['none — Aᶜ&B, A&Bᶜ, Aᶜ&Bᶜ are all independent','Aᶜ and B','A and Bᶜ','Aᶜ and Bᶜ'], answer:0 },
{ id:'S1.07.t01', clause:'S1.07', course:'S1', yield:3, type:'TRAP',
  claim:'P(A | B) = P(B | A).', verdict:false, because:'reversal',
  reasons:[{k:'reversal',label:'reversing the conditioning is the single most common error in the paper'},{k:'equal',label:'they are equal by symmetry of intersection'},{k:'indep',label:'they are equal when A and B are independent'},{k:'true',label:'the statement is correct'}] },
{ id:'S1.07.t02', clause:'S1.07', course:'S1', yield:3, type:'TRAP',
  claim:'Pairwise independence of A₁…Aₙ implies mutual independence.', verdict:false, because:'allsubsets',
  reasons:[{k:'allsubsets',label:'mutual independence needs the product rule for every sub-collection'},{k:'same',label:'the two notions are identical'},{k:'onlythree',label:'it fails only for n ≥ 4'},{k:'true',label:'the statement is correct'}] },
{ id:'S1.07.t03', clause:'S1.07', course:'S1', yield:3, type:'TRAP',
  claim:'A rare condition with a highly accurate test still gives a low posterior.', verdict:true, because:'baserate',
  reasons:[{k:'baserate',label:'the base rate dominates when the prior is small'},{k:'testbad',label:'it means the test is badly designed'},{k:'never',label:'a good test always gives a high posterior'},{k:'sample',label:'it depends only on sample size'}] },
{ id:'S1.07.ch01', clause:'S1.07', course:'S1', yield:3, type:'CHAIN',
  prompt:'The handbook’s recommended method for any two-way Bayes problem',
  steps:['Build a 2×2 contingency table with a convenient total (say 10,000)',
         'Fill in the cells from the prior and the likelihoods',
         'Read the relevant row or column total',
         'Divide the cell by that total — Bayes becomes division'] },
{ id:'S1.07.c03', clause:'S1.07', course:'S1', yield:3, type:'CLASSIFY',
  prompt:'Conditioning on B does what to the sample space?',
  options:['restricts it to B and rescales','removes B','doubles it','leaves it unchanged'], answer:0 }

]);
