/* FOUNDATION 44 — Corpus: Statistics for Data Science II
   Source clauses S2.01 … S2.13 of the Foundation Theory Handbook. */
window.CORPUS = (window.CORPUS || []).concat([

/* ── S2.01 Joint discrete distributions ─ yield 2 ──────────────────── */
{ id:'S2.01.f01', clause:'S2.01', course:'S2', yield:2, type:'FORMULA',
  prompt:'Marginal PMF of X from the joint PMF', answer:'p_X(x)=sum_y p(x,y)', accept:['sum out y'] },
{ id:'S2.01.f02', clause:'S2.01', course:'S2', yield:2, type:'FORMULA',
  prompt:'Conditional PMF p(x | y)', answer:'p(x,y)/p_Y(y)', accept:['joint over marginal of y'] },
{ id:'S2.01.f03', clause:'S2.01', course:'S2', yield:2, type:'FORMULA',
  prompt:'Independence of X and Y for discrete variables',
  answer:'p(x,y)=p_X(x)p_Y(y) for all (x,y)', accept:['the joint factors everywhere'] },
{ id:'S2.01.co01', clause:'S2.01', course:'S2', yield:2, type:'CONDITION',
  prompt:'Independence is claimed for a joint PMF whose support is {(x,y) : x ≤ y}.',
  verdict:'reject', because:'support',
  reasons:[{k:'support',label:'a non-rectangular support rules out independence whatever the formula looks like'},{k:'sums',label:'the probabilities do not sum to one'},{k:'neg',label:'the PMF takes negative values'},{k:'ok',label:'nothing is wrong'}] },
{ id:'S2.01.t01', clause:'S2.01', course:'S2', yield:2, type:'TRAP',
  claim:'The marginals determine the joint distribution.', verdict:false, because:'needindep',
  reasons:[{k:'needindep',label:'only if independence is additionally assumed'},{k:'always',label:'the marginals always determine the joint'},{k:'never',label:'the joint never determines the marginals'},{k:'discrete',label:'this holds only in the continuous case'}] },
{ id:'S2.01.c01', clause:'S2.01', course:'S2', yield:2, type:'CLASSIFY',
  prompt:'For n variables, mutual independence requires…',
  options:['the full factorisation p(x₁…xₙ) = Πp(xᵢ)','pairwise factorisation only','equal marginals','a rectangular support only'], answer:0 },

/* ── S2.02 Functions of random variables ─ yield 1 ─────────────────── */
{ id:'S2.02.f01', clause:'S2.02', course:'S2', yield:1, type:'FORMULA',
  prompt:'PMF of Y = g(X) for discrete X', answer:'p_Y(y)=sum_{x:g(x)=y} p_X(x)', accept:['sum over all preimages'] },
{ id:'S2.02.f02', clause:'S2.02', course:'S2', yield:1, type:'FORMULA',
  prompt:'Discrete convolution for the sum of independent X and Y',
  answer:'p_{X+Y}(z)=sum_x p_X(x)p_Y(z-x)', accept:['Σₓ pX(x)pY(z−x)'] },
{ id:'S2.02.f03', clause:'S2.02', course:'S2', yield:1, type:'FORMULA',
  prompt:'CDF of the maximum of independent X and Y', answer:'F_X(z)F_Y(z)', accept:['product of the CDFs'] },
{ id:'S2.02.f04', clause:'S2.02', course:'S2', yield:1, type:'FORMULA',
  prompt:'CDF of the minimum of independent X and Y',
  answer:'1-(1-F_X(z))(1-F_Y(z))', accept:['one minus the product of the survival functions'] },
{ id:'S2.02.co01', clause:'S2.02', course:'S2', yield:1, type:'CONDITION',
  prompt:'For the distribution of max(X,Y), work directly with the PMF rather than the CDF.',
  verdict:'reject', because:'usecdf',
  reasons:[{k:'usecdf',label:'go through the CDF — “max ≤ z” is a clean event, “max = z” is not'},{k:'usepmf',label:'the PMF is the right route'},{k:'indep',label:'independence is required either way'},{k:'ok',label:'nothing is wrong'}] },
{ id:'S2.02.c01', clause:'S2.02', course:'S2', yield:1, type:'CLASSIFY',
  prompt:'Binomial(m,p) + Binomial(n,p), independent, equals…',
  options:['Binomial(m+n, p)','Binomial(mn, p)','Poisson(mp+np)','Normal'], answer:0 },
{ id:'S2.02.c02', clause:'S2.02', course:'S2', yield:1, type:'CLASSIFY',
  prompt:'Poisson(λ₁) + Poisson(λ₂), independent, equals…',
  options:['Poisson(λ₁+λ₂)','Poisson(λ₁λ₂)','Binomial','Gamma'], answer:0 },
{ id:'S2.02.c03', clause:'S2.02', course:'S2', yield:1, type:'CLASSIFY',
  prompt:'When g is many-to-one (e.g. X²), probabilities…',
  options:['merge across preimages','transfer unchanged','vanish','double'], answer:0 },

/* ── S2.03 Expectation, variance, covariance ─ yield 3 ─────────────── */
{ id:'S2.03.f01', clause:'S2.03', course:'S2', yield:3, type:'FORMULA',
  prompt:'LOTUS — expectation of g(X) without finding its distribution',
  answer:'E[g(X)]=sum g(x)p(x)', accept:['∫g(x)f(x)dx in the continuous case'] },
{ id:'S2.03.f02', clause:'S2.03', course:'S2', yield:3, type:'FORMULA',
  prompt:'Linearity of expectation (no independence needed)',
  answer:'E[aX+bY+c]=aE[X]+bE[Y]+c', accept:['aE[X]+bE[Y]+c'] },
{ id:'S2.03.f03', clause:'S2.03', course:'S2', yield:3, type:'FORMULA',
  prompt:'Computational formula for the variance', answer:'Var(X)=E[X^2]-(E[X])^2', accept:['E[X²] − μ²'] },
{ id:'S2.03.f04', clause:'S2.03', course:'S2', yield:3, type:'FORMULA',
  prompt:'Var(aX + b) = ?', answer:'a^2 Var(X)', accept:['a²Var(X)'] },
{ id:'S2.03.f05', clause:'S2.03', course:'S2', yield:3, type:'FORMULA',
  prompt:'Covariance in computational form', answer:'Cov(X,Y)=E[XY]-E[X]E[Y]', accept:['E[XY] − μXμY'] },
{ id:'S2.03.f06', clause:'S2.03', course:'S2', yield:3, type:'FORMULA',
  prompt:'Var(X ± Y) in full', answer:'Var(X)+Var(Y)±2Cov(X,Y)', accept:['VarX + VarY ± 2Cov'] },
{ id:'S2.03.f07', clause:'S2.03', course:'S2', yield:3, type:'FORMULA',
  prompt:'Var(Σ aᵢXᵢ) in general',
  answer:'sum a_i^2 Var(X_i)+2 sum_{i<j} a_i a_j Cov(X_i,X_j)',
  accept:['Σaᵢ²Var + 2Σ_{i<j}aᵢaⱼCov'] },
{ id:'S2.03.f08', clause:'S2.03', course:'S2', yield:3, type:'FORMULA',
  prompt:'Correlation ρ in terms of covariance and SDs',
  answer:'Cov(X,Y)/(sigma_X sigma_Y)', accept:['Cov/(σXσY)'] },
{ id:'S2.03.f09', clause:'S2.03', course:'S2', yield:3, type:'FORMULA',
  prompt:'Bilinearity: Cov(aX + b, cY + d) = ?', answer:'ac Cov(X,Y)', accept:['acCov(X,Y)'] },
{ id:'S2.03.c01', clause:'S2.03', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'E[XY] = E[X]E[Y] requires…',
  options:['independence','nothing extra','equal variances','normality'], answer:0 },
{ id:'S2.03.c02', clause:'S2.03', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'|ρ| = 1 exactly when…',
  options:['Y is an exact linear function of X','X and Y are independent','Var X = Var Y','both are normal'], answer:0 },
{ id:'S2.03.t01', clause:'S2.03', course:'S2', yield:3, type:'TRAP',
  claim:'Uncorrelated implies independent.', verdict:false, because:'conversefails',
  reasons:[{k:'conversefails',label:'independent ⇒ uncorrelated, but not conversely — e.g. Y = X² with X symmetric'},{k:'true',label:'the statement is correct'},{k:'normal',label:'it fails only for normal variables'},{k:'never',label:'neither direction holds'}] },
{ id:'S2.03.t02', clause:'S2.03', course:'S2', yield:3, type:'TRAP',
  claim:'E[g(X)] = g(E[X]).', verdict:false, because:'onlylinear',
  reasons:[{k:'onlylinear',label:'this holds only when g is linear'},{k:'true',label:'the statement is correct'},{k:'convex',label:'it holds for all convex g'},{k:'never',label:'it never holds'}] },
{ id:'S2.03.t03', clause:'S2.03', course:'S2', yield:3, type:'TRAP',
  claim:'Var(X + Y) = Var(X) + Var(Y) for any X and Y.', verdict:false, because:'covterm',
  reasons:[{k:'covterm',label:'additive only when the covariance term vanishes'},{k:'true',label:'the statement is correct'},{k:'means',label:'variances never add'},{k:'sd',label:'standard deviations add instead'}] },

/* ── S2.04 Bounds and inequalities ─ yield 2 ───────────────────────── */
{ id:'S2.04.f01', clause:'S2.04', course:'S2', yield:2, type:'FORMULA',
  prompt:'Markov’s inequality (X ≥ 0, a > 0)', answer:'P(X>=a)<=E[X]/a', accept:['P(X ≥ a) ≤ μ/a'] },
{ id:'S2.04.f02', clause:'S2.04', course:'S2', yield:2, type:'FORMULA',
  prompt:'Chebyshev’s inequality in k-sigma form', answer:'P(|X-mu|>=k sigma)<=1/k^2', accept:['≤ 1/k²'] },
{ id:'S2.04.f03', clause:'S2.04', course:'S2', yield:2, type:'FORMULA',
  prompt:'Chebyshev’s inequality in epsilon form',
  answer:'P(|X-mu|>=eps)<=sigma^2/eps^2', accept:['≤ σ²/ε²'] },
{ id:'S2.04.c01', clause:'S2.04', course:'S2', yield:2, type:'CLASSIFY',
  prompt:'Chebyshev guarantees at least what fraction within 2 SDs?',
  options:['75%','68%','89%','95%'], answer:0 },
{ id:'S2.04.c02', clause:'S2.04', course:'S2', yield:2, type:'CLASSIFY',
  prompt:'Chebyshev guarantees at least what fraction within 3 SDs?',
  options:['89%','75%','99.7%','95%'], answer:0 },
{ id:'S2.04.d01', clause:'S2.04', course:'S2', yield:2, type:'DERIVE',
  prompt:'How is Chebyshev derived from Markov?',
  answer:'apply Markov to (X-mu)^2', accept:['apply Markov to the squared deviation'] },
{ id:'S2.04.ch01', clause:'S2.04', course:'S2', yield:2, type:'CHAIN',
  prompt:'From Markov to the weak law of large numbers',
  steps:['Markov’s inequality for a non-negative variable',
         'Apply it to (X − μ)² to obtain Chebyshev',
         'Apply Chebyshev to X̄ₙ, whose variance is σ²/n',
         'Let n → ∞: the bound σ²/(nε²) → 0, giving the WLLN'] },
{ id:'S2.04.co01', clause:'S2.04', course:'S2', yield:2, type:'CONDITION',
  prompt:'Use Chebyshev to answer a question that names the distribution as Normal(10, 4).',
  verdict:'reject', because:'exact',
  reasons:[{k:'exact',label:'a named distribution should be computed exactly — Chebyshev is for the distribution-free case'},{k:'nonneg',label:'Chebyshev needs a non-negative variable'},{k:'variance',label:'the variance is unknown'},{k:'ok',label:'nothing is wrong'}] },
{ id:'S2.04.dsc01', clause:'S2.04', course:'S2', yield:2, type:'DISCRIM',
  left:'Markov', right:'Chebyshev',
  items:[{t:'Requires X ≥ 0', side:'L'},{t:'Applies to any X with finite variance', side:'R'},
         {t:'Uses the mean only', side:'L'},{t:'Uses the mean and the variance', side:'R'},
         {t:'P(X ≥ a) ≤ E[X]/a', side:'L'},{t:'P(|X − μ| ≥ kσ) ≤ 1/k²', side:'R'}] },

/* ── S2.05 Continuous random variables ─ yield 3 ───────────────────── */
{ id:'S2.05.f01', clause:'S2.05', course:'S2', yield:3, type:'FORMULA',
  prompt:'Relation between the PDF and the CDF', answer:'f(x)=F\'(x), F(x)=int_{-inf}^{x} f', accept:['density is the derivative of the CDF'] },
{ id:'S2.05.f02', clause:'S2.05', course:'S2', yield:3, type:'FORMULA',
  prompt:'P(a < X ≤ b) in terms of the CDF', answer:'F(b)-F(a)', accept:['F(b) − F(a)'] },
{ id:'S2.05.f03', clause:'S2.05', course:'S2', yield:3, type:'FORMULA',
  prompt:'Standardising a normal variable', answer:'Z=(X-mu)/sigma', accept:['(X − μ)/σ'] },
{ id:'S2.05.f04', clause:'S2.05', course:'S2', yield:3, type:'FORMULA',
  prompt:'Symmetry identity for the standard normal CDF', answer:'Phi(-z)=1-Phi(z)', accept:['Φ(−z) = 1 − Φ(z)'] },
{ id:'S2.05.f05', clause:'S2.05', course:'S2', yield:3, type:'FORMULA',
  prompt:'Exponential(λ): give the PDF, CDF, mean and variance',
  answer:'f=lambda e^{-lambda x}; F=1-e^{-lambda x}; mean 1/lambda; var 1/lambda^2',
  accept:['λe^(−λx), 1−e^(−λx), 1/λ, 1/λ²'] },
{ id:'S2.05.f06', clause:'S2.05', course:'S2', yield:3, type:'FORMULA',
  prompt:'Uniform(a,b): give the mean and variance',
  answer:'mean (a+b)/2, var (b-a)^2/12', accept:['(a+b)/2 and (b−a)²/12'] },
{ id:'S2.05.f07', clause:'S2.05', course:'S2', yield:3, type:'FORMULA',
  prompt:'Distribution of aX + b when X ~ N(μ, σ²)',
  answer:'N(a mu+b, a^2 sigma^2)', accept:['normal with mean aμ+b and variance a²σ²'] },
{ id:'S2.05.f08', clause:'S2.05', course:'S2', yield:3, type:'FORMULA',
  prompt:'The empirical rule percentages for 1, 2 and 3 sigma',
  answer:'68%, 95%, 99.7%', accept:['68 95 99.7'] },
{ id:'S2.05.ch01', clause:'S2.05', course:'S2', yield:3, type:'CHAIN',
  prompt:'The CDF method for Y = g(X)',
  steps:['Write F_Y(y) = P(g(X) ≤ y)','Solve the inequality for X to express the event via F_X',
         'Differentiate to obtain f_Y(y) = dF_Y/dy'] },
{ id:'S2.05.c01', clause:'S2.05', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'The only continuous distribution that is memoryless is the…',
  options:['exponential','normal','uniform','gamma'], answer:0 },
{ id:'S2.05.c02', clause:'S2.05', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'The discrete counterpart of memorylessness belongs to the…',
  options:['geometric','binomial','Poisson','hypergeometric'], answer:0 },
{ id:'S2.05.t01', clause:'S2.05', course:'S2', yield:3, type:'TRAP',
  claim:'A density f(x) can never exceed 1.', verdict:false, because:'areanot',
  reasons:[{k:'areanot',label:'the density is not a probability — only the area under it is'},{k:'true',label:'the statement is correct'},{k:'normal',label:'it holds for the normal only'},{k:'cdf',label:'it holds for the CDF instead'}] },
{ id:'S2.05.t02', clause:'S2.05', course:'S2', yield:3, type:'TRAP',
  claim:'For continuous X, P(X = c) = 0 for every single point c.', verdict:true, because:'pointzero',
  reasons:[{k:'pointzero',label:'so < and ≤ may be used interchangeably'},{k:'false',label:'points carry positive probability'},{k:'onlynormal',label:'this is special to the normal'},{k:'undefined',label:'P(X = c) is undefined'}] },

/* ── S2.06 Joint continuous ─ yield 1 ──────────────────────────────── */
{ id:'S2.06.f01', clause:'S2.06', course:'S2', yield:1, type:'FORMULA',
  prompt:'Marginal density of X from a joint density', answer:'f_X(x)=int f(x,y) dy', accept:['integrate out y'] },
{ id:'S2.06.f02', clause:'S2.06', course:'S2', yield:1, type:'FORMULA',
  prompt:'Conditional density f(x | y)', answer:'f(x,y)/f_Y(y)', accept:['joint over the marginal of y'] },
{ id:'S2.06.co01', clause:'S2.06', course:'S2', yield:1, type:'CONDITION',
  prompt:'A joint density factors as f(x)g(y), so independence is declared — but the support is the triangle 0 < x < y < 1.',
  verdict:'reject', because:'prodregion',
  reasons:[{k:'prodregion',label:'independence needs the density to factor AND the support to be a product region'},{k:'nofactor',label:'the density does not factor'},{k:'normalise',label:'the density is not normalised'},{k:'ok',label:'nothing is wrong'}] },
{ id:'S2.06.c01', clause:'S2.06', course:'S2', yield:1, type:'CLASSIFY',
  prompt:'In joint continuous problems, most marks are lost on…',
  options:['the limits of integration','the algebra of the density','the choice of variable names','the final arithmetic'], answer:0 },
{ id:'S2.06.c02', clause:'S2.06', course:'S2', yield:1, type:'CLASSIFY',
  prompt:'A histogram with area normalised to 1 estimates the…',
  options:['density','CDF','MGF','quantile function'], answer:0 },

/* ── S2.07 Samples and limit theorems ─ yield 2 ────────────────────── */
{ id:'S2.07.f01', clause:'S2.07', course:'S2', yield:2, type:'FORMULA',
  prompt:'Mean and variance of the sample mean X̄',
  answer:'E[Xbar]=mu, Var(Xbar)=sigma^2/n', accept:['μ and σ²/n'] },
{ id:'S2.07.f02', clause:'S2.07', course:'S2', yield:2, type:'FORMULA',
  prompt:'The standard error of the mean', answer:'sigma/sqrt(n)', accept:['σ/√n'] },
{ id:'S2.07.f03', clause:'S2.07', course:'S2', yield:2, type:'FORMULA',
  prompt:'E[S²] for the sample variance with divisor n − 1', answer:'sigma^2', accept:['σ² — it is unbiased'] },
{ id:'S2.07.f04', clause:'S2.07', course:'S2', yield:2, type:'FORMULA',
  prompt:'Statement of the weak law of large numbers',
  answer:'P(|Xbar_n-mu|>eps)->0 as n->infinity', accept:['the sample mean converges in probability to μ'] },
{ id:'S2.07.c01', clause:'S2.07', course:'S2', yield:2, type:'CLASSIFY',
  prompt:'A statistic is any function of the sample that…',
  options:['contains no unknown parameters','is unbiased','is normally distributed','has finite variance'], answer:0 },
{ id:'S2.07.c02', clause:'S2.07', course:'S2', yield:2, type:'CLASSIFY',
  prompt:'The empirical distribution function F̂ₙ is…',
  options:['unbiased and consistent for F','biased','undefined for continuous data','equal to the density'], answer:0 },

/* ── S2.08 MGFs and the CLT ─ yield 3 ──────────────────────────────── */
{ id:'S2.08.f01', clause:'S2.08', course:'S2', yield:3, type:'FORMULA',
  prompt:'Definition of the moment generating function', answer:'M_X(t)=E[e^{tX}]', accept:['E[e^tX]'] },
{ id:'S2.08.f02', clause:'S2.08', course:'S2', yield:3, type:'FORMULA',
  prompt:'Getting the k-th moment from the MGF', answer:'E[X^k]=M^{(k)}(0)', accept:['the k-th derivative at 0'] },
{ id:'S2.08.f03', clause:'S2.08', course:'S2', yield:3, type:'FORMULA',
  prompt:'Variance from the MGF', answer:'M\'\'(0)-[M\'(0)]^2', accept:['M″(0) − (M′(0))²'] },
{ id:'S2.08.f04', clause:'S2.08', course:'S2', yield:3, type:'FORMULA',
  prompt:'MGF of aX + b', answer:'e^{bt}M_X(at)', accept:['e^(bt)M(at)'] },
{ id:'S2.08.f05', clause:'S2.08', course:'S2', yield:3, type:'FORMULA',
  prompt:'MGF of a sum of independent variables', answer:'M_X(t)M_Y(t)', accept:['the product of the MGFs'] },
{ id:'S2.08.f06', clause:'S2.08', course:'S2', yield:3, type:'FORMULA',
  prompt:'The CLT statement for the standardised sample mean',
  answer:'(Xbar-mu)/(sigma/sqrt n) -> N(0,1) in distribution',
  accept:['Zₙ converges in distribution to standard normal'] },
{ id:'S2.08.f07', clause:'S2.08', course:'S2', yield:3, type:'FORMULA',
  prompt:'Continuity correction for P(X ≤ k) when approximating a discrete variable',
  answer:'P(Y<=k+0.5)', accept:['add one half'] },
{ id:'S2.08.f08', clause:'S2.08', course:'S2', yield:3, type:'FORMULA',
  prompt:'The four normal-sampling results — name the distribution of (n−1)S²/σ²',
  answer:'chi-squared with n-1 df', accept:['χ²_{n−1}'] },
{ id:'S2.08.f09', clause:'S2.08', course:'S2', yield:3, type:'FORMULA',
  prompt:'Distribution of (X̄ − μ)/(S/√n) when sampling from a normal',
  answer:'t with n-1 df', accept:['t_{n−1}'] },
{ id:'S2.08.f10', clause:'S2.08', course:'S2', yield:3, type:'FORMULA',
  prompt:'Distribution of the ratio (S₁²/σ₁²)/(S₂²/σ₂²)',
  answer:'F with n1-1 and n2-1 df', accept:['F_{n₁−1, n₂−1}'] },
{ id:'S2.08.c01', clause:'S2.08', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'The CLT assumes what about the parent distribution?',
  options:['only a finite variance','normality','symmetry','a known mean'], answer:0 },
{ id:'S2.08.c02', clause:'S2.08', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'X̄ and S² are independent when sampling from which distribution?',
  options:['the normal — and it is unique in this','any distribution','the exponential','the uniform'], answer:0 },
{ id:'S2.08.c03', clause:'S2.08', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'χ²ₖ has mean and variance…', options:['k and 2k','k and k','2k and k','k and k²'], answer:0 },
{ id:'S2.08.c04', clause:'S2.08', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'The t distribution compared with N(0,1) is…',
  options:['symmetric but heavier-tailed, converging to it as df → ∞','skewed right','identical','lighter-tailed'], answer:0 },
{ id:'S2.08.dsc01', clause:'S2.08', course:'S2', yield:3, type:'DISCRIM',
  left:'Law of large numbers', right:'Central limit theorem',
  items:[{t:'Says X̄ converges to μ', side:'L'},{t:'Says how the error is distributed', side:'R'},
         {t:'Proved via Chebyshev', side:'L'},{t:'Gives an approximate normal distribution', side:'R'},
         {t:'A statement about location', side:'L'},{t:'A statement about shape', side:'R'}] },

/* ── S2.09 Point estimation ─ yield 3 ──────────────────────────────── */
{ id:'S2.09.f01', clause:'S2.09', course:'S2', yield:3, type:'FORMULA',
  prompt:'Definition of bias', answer:'E[thetahat]-theta', accept:['E[θ̂] − θ'] },
{ id:'S2.09.f02', clause:'S2.09', course:'S2', yield:3, type:'FORMULA',
  prompt:'The MSE decomposition', answer:'MSE=Var(thetahat)+Bias^2', accept:['variance plus squared bias'] },
{ id:'S2.09.f03', clause:'S2.09', course:'S2', yield:3, type:'FORMULA',
  prompt:'The log-likelihood ℓ(θ) for an i.i.d. sample',
  answer:'sum log f(x_i;theta)', accept:['Σ log f(xᵢ;θ)'] },
{ id:'S2.09.f04', clause:'S2.09', course:'S2', yield:3, type:'FORMULA',
  prompt:'The method-of-moments principle',
  answer:'equate population moments to sample moments and solve',
  accept:['E[X]=x̄, E[X²]=Σx²/n, …'] },
{ id:'S2.09.ch01', clause:'S2.09', course:'S2', yield:3, type:'CHAIN',
  prompt:'The MLE procedure',
  steps:['Write the likelihood L(θ) = Π f(xᵢ; θ)','Take logs to get ℓ(θ)',
         'Set dℓ/dθ = 0','Solve for θ̂',
         'Verify it is a maximum (second derivative, or check the boundary)'] },
{ id:'S2.09.c01', clause:'S2.09', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'MLE of p for Bernoulli/Binomial data is…',
  options:['x̄','1/x̄','max xᵢ','Σx²/n'], answer:0 },
{ id:'S2.09.c02', clause:'S2.09', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'MLE of λ for Exponential data is…',
  options:['1/x̄','x̄','max xᵢ','n/Σx²'], answer:0 },
{ id:'S2.09.c03', clause:'S2.09', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'MLE of θ for Uniform(0, θ) is…',
  options:['max xᵢ','x̄','2x̄','min xᵢ'], answer:0 },
{ id:'S2.09.c04', clause:'S2.09', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'The MLE of σ² for a normal uses which divisor?',
  options:['n — and is therefore biased','n − 1, unbiased','n + 1','n − 2'], answer:0 },
{ id:'S2.09.co01', clause:'S2.09', course:'S2', yield:3, type:'CONDITION',
  prompt:'Find the MLE of θ for Uniform(0,θ) by setting dℓ/dθ = 0.',
  verdict:'reject', because:'boundary',
  reasons:[{k:'boundary',label:'L is decreasing wherever positive — the maximum is at the boundary θ = max xᵢ'},{k:'nolog',label:'the log cannot be taken'},{k:'notiid',label:'the sample is not i.i.d.'},{k:'ok',label:'nothing is wrong'}] },
{ id:'S2.09.t01', clause:'S2.09', course:'S2', yield:3, type:'TRAP',
  claim:'S is an unbiased estimator of σ because S² is unbiased for σ².', verdict:false, because:'nonlinear',
  reasons:[{k:'nonlinear',label:'unbiasedness does not survive a non-linear transformation'},{k:'true',label:'the statement is correct'},{k:'sqrt',label:'square roots always preserve unbiasedness'},{k:'large',label:'it holds only for large n'}] },
{ id:'S2.09.dsc01', clause:'S2.09', course:'S2', yield:3, type:'DISCRIM',
  left:'Method of moments', right:'Maximum likelihood',
  items:[{t:'Equate sample and population moments', side:'L'},{t:'Maximise the likelihood function', side:'R'},
         {t:'Can give estimates outside the parameter space', side:'L'},{t:'Has the invariance property', side:'R'},
         {t:'Simple and always available', side:'L'},{t:'Consistent and asymptotically normal', side:'R'}] },
{ id:'S2.09.c05', clause:'S2.09', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'The invariance property of the MLE says that…',
  options:['g(θ̂) is the MLE of g(θ)','θ̂ is unbiased','θ̂ has minimum variance','θ̂ is normal'], answer:0 },

/* ── S2.10 Confidence intervals ─ yield 3 ──────────────────────────── */
{ id:'S2.10.f01', clause:'S2.10', course:'S2', yield:3, type:'FORMULA',
  prompt:'CI for μ with σ known', answer:'xbar ± z_{alpha/2} sigma/sqrt(n)', accept:['x̄ ± z σ/√n'] },
{ id:'S2.10.f02', clause:'S2.10', course:'S2', yield:3, type:'FORMULA',
  prompt:'CI for μ with σ unknown, normal population',
  answer:'xbar ± t_{alpha/2,n-1} s/sqrt(n)', accept:['x̄ ± t s/√n'] },
{ id:'S2.10.f03', clause:'S2.10', course:'S2', yield:3, type:'FORMULA',
  prompt:'CI for a proportion p',
  answer:'phat ± z_{alpha/2} sqrt(phat(1-phat)/n)', accept:['p̂ ± z√(p̂(1−p̂)/n)'] },
{ id:'S2.10.f04', clause:'S2.10', course:'S2', yield:3, type:'FORMULA',
  prompt:'CI for σ² in a normal population',
  answer:'((n-1)s^2/chi^2_{alpha/2}, (n-1)s^2/chi^2_{1-alpha/2})',
  accept:['(n−1)s² over the two chi-square critical values'] },
{ id:'S2.10.f05', clause:'S2.10', course:'S2', yield:3, type:'FORMULA',
  prompt:'Sample size for a given margin of error E',
  answer:'n=(z_{alpha/2} sigma/E)^2', accept:['(zσ/E)², rounded up'] },
{ id:'S2.10.f06', clause:'S2.10', course:'S2', yield:3, type:'FORMULA',
  prompt:'The three common z critical values (0.10, 0.05, 0.01 two-sided)',
  answer:'1.645, 1.96, 2.576', accept:['z0.05=1.645, z0.025=1.96, z0.005=2.576'] },
{ id:'S2.10.c01', clause:'S2.10', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'CI width shrinks like…', options:['1/√n','1/n','1/n²','log n'], answer:0 },
{ id:'S2.10.c02', clause:'S2.10', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'To quarter the width of a CI you need how much more data?',
  options:['16×','4×','2×','8×'], answer:0 },
{ id:'S2.10.t01', clause:'S2.10', course:'S2', yield:3, type:'TRAP',
  claim:'There is a 95% probability that μ lies in this particular interval.', verdict:false, because:'repeated',
  reasons:[{k:'repeated',label:'the parameter is fixed and the interval is random — the 95% refers to repeated sampling'},{k:'true',label:'the statement is correct'},{k:'bayes',label:'it is correct only for large n'},{k:'ci99',label:'it applies at 99% instead'}] },
{ id:'S2.10.co01', clause:'S2.10', course:'S2', yield:3, type:'CONDITION',
  prompt:'Sample size computed as n = (zσ/E)² = 42.3, so n = 42 is reported.',
  verdict:'reject', because:'roundup',
  reasons:[{k:'roundup',label:'always round the sample size UP'},{k:'rounddown',label:'rounding down is correct'},{k:'nearest',label:'round to the nearest integer'},{k:'ok',label:'nothing is wrong'}] },

/* ── S2.11 Bayesian estimation ─ yield 2 ───────────────────────────── */
{ id:'S2.11.f01', clause:'S2.11', course:'S2', yield:2, type:'FORMULA',
  prompt:'The posterior, up to proportionality',
  answer:'posterior ∝ likelihood × prior', accept:['π(θ|x) ∝ f(x|θ)π(θ)'] },
{ id:'S2.11.c01', clause:'S2.11', course:'S2', yield:2, type:'CLASSIFY',
  prompt:'The posterior MEAN minimises which loss?',
  options:['squared-error loss','absolute loss','0–1 loss','hinge loss'], answer:0 },
{ id:'S2.11.c02', clause:'S2.11', course:'S2', yield:2, type:'CLASSIFY',
  prompt:'The MAP estimate coincides with the MLE when the prior is…',
  options:['flat','conjugate','normal','improper'], answer:0 },
{ id:'S2.11.c03', clause:'S2.11', course:'S2', yield:2, type:'CLASSIFY',
  prompt:'Beta prior with a Binomial likelihood gives which posterior?',
  options:['Beta(α+Σxᵢ, β+n−Σxᵢ)','Gamma','Normal','Beta(α, β)'], answer:0 },
{ id:'S2.11.c04', clause:'S2.11', course:'S2', yield:2, type:'CLASSIFY',
  prompt:'Gamma prior with a Poisson likelihood gives…',
  options:['Gamma(α+Σxᵢ, β+n)','Beta','Normal','Poisson'], answer:0 },
{ id:'S2.11.f02', clause:'S2.11', course:'S2', yield:2, type:'FORMULA',
  prompt:'Means of the Beta(α,β) and Gamma(α,β) distributions',
  answer:'alpha/(alpha+beta) and alpha/beta', accept:['α/(α+β); α/β'] },
{ id:'S2.11.dsc01', clause:'S2.11', course:'S2', yield:2, type:'DISCRIM',
  left:'Confidence interval', right:'Credible interval',
  items:[{t:'The parameter is fixed; the interval is random', side:'L'},{t:'The parameter is treated as random', side:'R'},
         {t:'Coverage is over repeated sampling', side:'L'},{t:'Genuinely contains θ with the stated probability', side:'R'},
         {t:'Frequentist', side:'L'},{t:'Bayesian, read off the posterior', side:'R'}] },
{ id:'S2.11.c05', clause:'S2.11', course:'S2', yield:2, type:'CLASSIFY',
  prompt:'As n grows, the prior…',
  options:['washes out as the likelihood dominates','dominates the likelihood','stays equally influential','becomes the posterior'], answer:0 },

/* ── S2.12 Hypothesis testing framework ─ yield 3 ──────────────────── */
{ id:'S2.12.f01', clause:'S2.12', course:'S2', yield:3, type:'FORMULA',
  prompt:'Definition of the p-value',
  answer:'P(statistic at least as extreme as observed | H0 true)',
  accept:['the probability under H₀ of a result at least as extreme'] },
{ id:'S2.12.f02', clause:'S2.12', course:'S2', yield:3, type:'FORMULA',
  prompt:'The p-value decision rule', answer:'reject H0 iff p<=alpha', accept:['reject when p ≤ α'] },
{ id:'S2.12.f03', clause:'S2.12', course:'S2', yield:3, type:'FORMULA',
  prompt:'Two-tailed p-value from an observed z', answer:'2P(Z>=|z_obs|)', accept:['2×the one-tail area'] },
{ id:'S2.12.f04', clause:'S2.12', course:'S2', yield:3, type:'FORMULA',
  prompt:'Define the size α and the power of a test',
  answer:'alpha=P(reject H0|H0 true); power=1-beta', accept:['Type I rate; 1 − Type II rate'] },
{ id:'S2.12.f05', clause:'S2.12', course:'S2', yield:3, type:'FORMULA',
  prompt:'The Neyman–Pearson rejection rule for two simple hypotheses',
  answer:'reject when L(theta1)/L(theta0)>k', accept:['likelihood ratio exceeds k'] },
{ id:'S2.12.f06', clause:'S2.12', course:'S2', yield:3, type:'FORMULA',
  prompt:'Asymptotic distribution of −2 ln Λ for the generalised LRT',
  answer:'chi^2_r with r constrained parameters', accept:['χ²ᵣ'] },
{ id:'S2.12.c01', clause:'S2.12', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'Rejecting H₀ when it is true is…',
  options:['a Type I error, probability α','a Type II error','correct','power'], answer:0 },
{ id:'S2.12.c02', clause:'S2.12', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'Failing to reject H₀ when it is false is…',
  options:['a Type II error, probability β','a Type I error','correct','the size'], answer:0 },
{ id:'S2.12.c03', clause:'S2.12', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'Power increases with all of these EXCEPT…',
  options:['smaller α','larger n','a larger true effect','a smaller σ'], answer:0 },
{ id:'S2.12.c04', clause:'S2.12', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'H₀ always contains…',
  options:['equality','the effect of interest','the alternative','the p-value'], answer:0 },
{ id:'S2.12.dsc01', clause:'S2.12', course:'S2', yield:3, type:'DISCRIM',
  left:'Type I error', right:'Type II error',
  items:[{t:'Rejecting a true H₀', side:'L'},{t:'Failing to reject a false H₀', side:'R'},
         {t:'Probability α', side:'L'},{t:'Probability β', side:'R'},
         {t:'Controlled by the significance level', side:'L'},{t:'Its complement is the power', side:'R'},
         {t:'A false positive', side:'L'},{t:'A false negative', side:'R'}] },
{ id:'S2.12.t01', clause:'S2.12', course:'S2', yield:3, type:'TRAP',
  claim:'The p-value is the probability that H₀ is true.', verdict:false, because:'notposterior',
  reasons:[{k:'notposterior',label:'it is computed ASSUMING H₀, and is not P(H₀ | data)'},{k:'true',label:'the statement is correct'},{k:'chance',label:'it is the probability the result was due to chance'},{k:'alpha',label:'it equals α'}] },
{ id:'S2.12.t02', clause:'S2.12', course:'S2', yield:3, type:'TRAP',
  claim:'“Fail to reject H₀” means H₀ is accepted as true.', verdict:false, because:'absence',
  reasons:[{k:'absence',label:'absence of evidence is not evidence of absence'},{k:'true',label:'the statement is correct'},{k:'power',label:'it is true when the power is high'},{k:'large',label:'it is true for large n'}] },
{ id:'S2.12.t03', clause:'S2.12', course:'S2', yield:3, type:'TRAP',
  claim:'A statistically significant result is practically important.', verdict:false, because:'hugen',
  reasons:[{k:'hugen',label:'a huge n makes trivial effects significant'},{k:'true',label:'the statement is correct'},{k:'alpha',label:'it depends only on α'},{k:'never',label:'significance is never meaningful'}] },
{ id:'S2.12.c05', clause:'S2.12', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'A two-tailed test of μ = μ₀ at level α rejects exactly when…',
  options:['μ₀ falls outside the 100(1−α)% CI','μ₀ is inside the CI','the CI is narrow','p > α'], answer:0 },

/* ── S2.13 The test battery ─ yield 3 ──────────────────────────────── */
{ id:'S2.13.f01', clause:'S2.13', course:'S2', yield:3, type:'FORMULA',
  prompt:'One-sample z statistic', answer:'z=(xbar-mu0)/(sigma/sqrt n)', accept:['(x̄ − μ₀)/(σ/√n)'] },
{ id:'S2.13.f02', clause:'S2.13', course:'S2', yield:3, type:'FORMULA',
  prompt:'One-sample t statistic and its df',
  answer:'t=(xbar-mu0)/(s/sqrt n), df=n-1', accept:['(x̄−μ₀)/(s/√n) with n−1 df'] },
{ id:'S2.13.f03', clause:'S2.13', course:'S2', yield:3, type:'FORMULA',
  prompt:'Pooled variance s_p² for the two-sample t',
  answer:'((n1-1)s1^2+(n2-1)s2^2)/(n1+n2-2)', accept:['weighted average of the two variances'] },
{ id:'S2.13.f04', clause:'S2.13', course:'S2', yield:3, type:'FORMULA',
  prompt:'Pooled t statistic and its df',
  answer:'t=((xbar1-xbar2)-delta0)/(s_p sqrt(1/n1+1/n2)), df=n1+n2-2',
  accept:['difference over s_p√(1/n₁+1/n₂), df n₁+n₂−2'] },
{ id:'S2.13.f05', clause:'S2.13', course:'S2', yield:3, type:'FORMULA',
  prompt:'Welch t — how does its denominator differ from the pooled one?',
  answer:'sqrt(s1^2/n1+s2^2/n2)', accept:['√(s₁²/n₁ + s₂²/n₂), approximate df'] },
{ id:'S2.13.f06', clause:'S2.13', course:'S2', yield:3, type:'FORMULA',
  prompt:'Paired t statistic and its df',
  answer:'t=(dbar-delta0)/(s_d/sqrt n), df=n-1', accept:['work with the differences dᵢ'] },
{ id:'S2.13.f07', clause:'S2.13', course:'S2', yield:3, type:'FORMULA',
  prompt:'z statistic for a proportion — and which p goes in the SE?',
  answer:'z=(phat-p0)/sqrt(p0(1-p0)/n); use p0 not phat',
  accept:['(p̂−p₀)/√(p₀(1−p₀)/n)'] },
{ id:'S2.13.f08', clause:'S2.13', course:'S2', yield:3, type:'FORMULA',
  prompt:'Chi-square statistic for one variance, and its df',
  answer:'chi^2=(n-1)s^2/sigma0^2, df=n-1', accept:['(n−1)s²/σ₀² with n−1 df'] },
{ id:'S2.13.f09', clause:'S2.13', course:'S2', yield:3, type:'FORMULA',
  prompt:'F statistic for comparing two variances, and its df',
  answer:'F=s1^2/s2^2, df=(n1-1,n2-1)', accept:['ratio of sample variances'] },
{ id:'S2.13.f10', clause:'S2.13', course:'S2', yield:3, type:'FORMULA',
  prompt:'The chi-square count statistic', answer:'sum (O_i-E_i)^2/E_i', accept:['Σ(O−E)²/E'] },
{ id:'S2.13.f11', clause:'S2.13', course:'S2', yield:3, type:'FORMULA',
  prompt:'df for a chi-square goodness-of-fit test',
  answer:'k-1-m', accept:['categories minus one minus parameters estimated'] },
{ id:'S2.13.f12', clause:'S2.13', course:'S2', yield:3, type:'FORMULA',
  prompt:'df and expected counts for an r×c independence test',
  answer:'df=(r-1)(c-1), E_ij=row_i*col_j/n', accept:['(r−1)(c−1); row×column/n'] },
{ id:'S2.13.f13', clause:'S2.13', course:'S2', yield:3, type:'FORMULA',
  prompt:'The Kolmogorov–Smirnov statistic', answer:'D=sup|Fhat_n(x)-F0(x)|', accept:['largest gap between empirical and hypothesised CDF'] },
{ id:'S2.13.c01', clause:'S2.13', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'The chi-square test on counts is always…',
  options:['right-tailed','left-tailed','two-tailed','either'], answer:0 },
{ id:'S2.13.c02', clause:'S2.13', course:'S2', yield:3, type:'CLASSIFY',
  prompt:'Validity condition for the chi-square count tests is…',
  options:['all Eᵢ ≥ 5','all Oᵢ ≥ 5','n ≥ 30','normality'], answer:0 },
{ id:'S2.13.dsc01', clause:'S2.13', course:'S2', yield:3, type:'DISCRIM',
  left:'Pooled t', right:'Welch t',
  items:[{t:'Assumes equal unknown variances', side:'L'},{t:'Allows unequal variances', side:'R'},
         {t:'Uses s_p²', side:'L'},{t:'Uses s₁²/n₁ + s₂²/n₂', side:'R'},
         {t:'df = n₁ + n₂ − 2', side:'L'},{t:'df is approximate', side:'R'}] },
{ id:'S2.13.dsc02', clause:'S2.13', course:'S2', yield:3, type:'DISCRIM',
  left:'Paired t', right:'Two-sample t',
  items:[{t:'Same units measured twice', side:'L'},{t:'Two independent groups', side:'R'},
         {t:'Work with the differences dᵢ', side:'L'},{t:'Work with the two group means', side:'R'},
         {t:'df = n − 1', side:'L'},{t:'df = n₁ + n₂ − 2 (pooled)', side:'R'}] },
{ id:'S2.13.co01', clause:'S2.13', course:'S2', yield:3, type:'CONDITION',
  prompt:'Two independent groups, variances unknown and clearly unequal — use the pooled t.',
  verdict:'reject', because:'welch',
  reasons:[{k:'welch',label:'unequal variances call for Welch’s t'},{k:'paired',label:'the data should be treated as paired'},{k:'df',label:'the degrees of freedom are wrong'},{k:'normality',label:'normality fails'}] },
{ id:'S2.13.co02', clause:'S2.13', course:'S2', yield:3, type:'CONDITION',
  prompt:'Reaction time measured before and after treatment on the same 22 subjects — use a two-sample t.',
  verdict:'reject', because:'paired',
  reasons:[{k:'paired',label:'before/after on the same units is paired — ignoring the pairing loses power'},{k:'welch',label:'Welch’s t is needed'},{k:'z',label:'a z test is needed'},{k:'ok',label:'nothing is wrong'}] },
{ id:'S2.13.co03', clause:'S2.13', course:'S2', yield:3, type:'CONDITION',
  prompt:'Chi-square goodness of fit where one cell has an expected count of 3.',
  verdict:'reject', because:'pool',
  reasons:[{k:'pool',label:'pool sparse categories until every expected count is at least 5'},{k:'observed',label:'the observed counts are what matter'},{k:'df',label:'the df must be increased'},{k:'ok',label:'nothing is wrong'}] },
{ id:'S2.13.co04', clause:'S2.13', course:'S2', yield:3, type:'CONDITION',
  prompt:'Testing a proportion, the standard error is computed using p̂ rather than p₀.',
  verdict:'reject', because:'usep0',
  reasons:[{k:'usep0',label:'under H₀ the SE uses p₀, not p̂'},{k:'usephat',label:'p̂ is correct in a test'},{k:'either',label:'either may be used'},{k:'ok',label:'nothing is wrong'}] },
{ id:'S2.13.t01', clause:'S2.13', course:'S2', yield:3, type:'TRAP',
  claim:'Degrees of freedom should be written down before computing anything.', verdict:true, because:'dfmarks',
  reasons:[{k:'dfmarks',label:'df is where marks disappear — fix it first'},{k:'later',label:'df is only needed at the very end'},{k:'never',label:'df does not matter'},{k:'auto',label:'df is always n − 1'}] }

]);
