/* FOUNDATION 44 — Corpus: Mathematics for Data Science I
   Source clauses M1.01 … M1.08 of the Foundation Theory Handbook. */
window.CORPUS = (window.CORPUS || []).concat([

/* ── M1.01 Number systems ─ yield 1 ───────────────────────────────── */
{ id:'M1.01.c01', clause:'M1.01', course:'M1', yield:1, type:'CLASSIFY',
  prompt:'Which set is NOT closed under division (by a non-zero element)?',
  options:['ℤ (integers)','ℚ (rationals)','ℝ (reals)','ℂ (complex)'], answer:0 },
{ id:'M1.01.c02', clause:'M1.01', course:'M1', yield:1, type:'CLASSIFY',
  prompt:'ℝ is extended to ℂ because ℝ fails at…',
  options:['√−1','3 ÷ 5','3 − 5','√2'], answer:0 },
{ id:'M1.01.t01', clause:'M1.01', course:'M1', yield:1, type:'TRAP',
  claim:'ℤ is a field.', verdict:false, because:'noinv',
  reasons:[{k:'noinv',label:'it lacks multiplicative inverses'},{k:'noadd',label:'it lacks additive inverses'},{k:'notclosed',label:'it is not closed under ×'},{k:'noident',label:'it has no identity elements'}] },
{ id:'M1.01.t02', clause:'M1.01', course:'M1', yield:1, type:'TRAP',
  claim:'ℂ is an ordered field.', verdict:false, because:'noorder',
  reasons:[{k:'noorder',label:'ℂ cannot be ordered compatibly with its arithmetic'},{k:'notclosed',label:'ℂ is not closed under roots'},{k:'noinv',label:'ℂ lacks inverses'},{k:'notfield',label:'ℂ is not a field at all'}] },
{ id:'M1.01.c03', clause:'M1.01', course:'M1', yield:1, type:'CLASSIFY',
  prompt:'p/q in lowest terms has a terminating decimal expansion exactly when q has only which prime factors?',
  options:['2 and 5','2 and 3','3 and 5','any primes'], answer:0 },
{ id:'M1.01.t03', clause:'M1.01', course:'M1', yield:1, type:'TRAP',
  claim:'1 is a prime number.', verdict:false, because:'neither',
  reasons:[{k:'neither',label:'1 is neither prime nor composite'},{k:'toosmall',label:'primes must exceed 2'},{k:'even',label:'1 is even'},{k:'unit',label:'1 has three divisors'}] },
{ id:'M1.01.f01', clause:'M1.01', course:'M1', yield:1, type:'FORMULA',
  prompt:'Number of positive divisors of n = p₁^a₁ ⋯ p_k^a_k',
  answer:'prod(ai+1)', accept:['product of (a_i+1)','(a1+1)(a2+1)...(ak+1)','prod (a_i + 1)'] },
{ id:'M1.01.f02', clause:'M1.01', course:'M1', yield:1, type:'FORMULA',
  prompt:'Relation between gcd, lcm and the product of a and b',
  answer:'gcd(a,b)*lcm(a,b)=ab', accept:['gcd*lcm=ab','gcd(a,b)lcm(a,b)=ab'] },
{ id:'M1.01.f03', clause:'M1.01', course:'M1', yield:1, type:'FORMULA',
  prompt:'For z = a + ib, write |z| in terms of a and b',
  answer:'sqrt(a^2+b^2)', accept:['(a^2+b^2)^(1/2)','root(a^2+b^2)'] },
{ id:'M1.01.f04', clause:'M1.01', course:'M1', yield:1, type:'FORMULA',
  prompt:'Express z⁻¹ using the conjugate and modulus of z',
  answer:'conj(z)/|z|^2', accept:['zbar/|z|^2','conjugate(z)/|z|^2','\\bar z/|z|^2'] },
{ id:'M1.01.d01', clause:'M1.01', course:'M1', yield:1, type:'DERIVE',
  prompt:'√2 is irrational — state the key move of the contradiction proof.',
  answer:'p^2=2q^2 so p even, p=2k gives q even, contradicting gcd(p,q)=1',
  accept:['p even implies q even contradicting lowest terms','both p and q turn out even, contradicting gcd=1'] },

/* ── M1.02 Sets, cardinality, counting ─ yield 2 ───────────────────── */
{ id:'M1.02.f01', clause:'M1.02', course:'M1', yield:2, type:'FORMULA',
  prompt:'Size of the power set of A, where |A| = n',
  answer:'2^n', accept:['2**n'] },
{ id:'M1.02.f02', clause:'M1.02', course:'M1', yield:2, type:'FORMULA',
  prompt:'Inclusion–exclusion for two sets: |A ∪ B| = ?',
  answer:'|A|+|B|-|A∩B|', accept:['|A|+|B|-|AnB|','n(A)+n(B)-n(A and B)'] },
{ id:'M1.02.f03', clause:'M1.02', course:'M1', yield:2, type:'FORMULA',
  prompt:'Inclusion–exclusion for three sets: |A ∪ B ∪ C| = ?',
  answer:'|A|+|B|+|C|-|A∩B|-|A∩C|-|B∩C|+|A∩B∩C|',
  accept:['sum single - sum pairs + triple'] },
{ id:'M1.02.f04', clause:'M1.02', course:'M1', yield:2, type:'FORMULA',
  prompt:'De Morgan: (A ∪ B)ᶜ = ?', answer:'A^c∩B^c', accept:['Ac and Bc','A\'∩B\'','complement(A) intersect complement(B)'] },
{ id:'M1.02.f05', clause:'M1.02', course:'M1', yield:2, type:'FORMULA',
  prompt:'Set difference A \\ B written using complement and intersection',
  answer:'A∩B^c', accept:['A and Bc','A∩B\''] },
{ id:'M1.02.f06', clause:'M1.02', course:'M1', yield:2, type:'FORMULA',
  prompt:'Symmetric difference A △ B in terms of unions and intersections',
  answer:'(A∪B)\\(A∩B)', accept:['(A\\B)∪(B\\A)','(A-B)u(B-A)'] },
{ id:'M1.02.t01', clause:'M1.02', course:'M1', yield:2, type:'TRAP',
  claim:'{1} ∈ {1, 2}', verdict:false, because:'subsetnotelem',
  reasons:[{k:'subsetnotelem',label:'{1} is a subset, not an element, of {1,2}'},{k:'wrongsize',label:'the sets have different sizes'},{k:'notordered',label:'sets are unordered'},{k:'empty',label:'{1} is empty'}] },
{ id:'M1.02.t02', clause:'M1.02', course:'M1', yield:2, type:'TRAP',
  claim:'∅ and {∅} are the same set.', verdict:false, because:'oneelem',
  reasons:[{k:'oneelem',label:'{∅} has one element; ∅ has none'},{k:'bothempty',label:'both are empty but differently written'},{k:'notset',label:'{∅} is not a set'},{k:'infinite',label:'{∅} is infinite'}] },
{ id:'M1.02.t03', clause:'M1.02', course:'M1', yield:2, type:'TRAP',
  claim:'An infinite set can be in bijection with a proper subset of itself.', verdict:true, because:'defofinf',
  reasons:[{k:'defofinf',label:'that is precisely the definition of infinite'},{k:'paradox',label:'it is a genuine paradox in set theory'},{k:'onlyN',label:'only ℕ has this property'},{k:'false',label:'it violates cardinality'}] },
{ id:'M1.02.c01', clause:'M1.02', course:'M1', yield:2, type:'CLASSIFY',
  prompt:'Which set is uncountable?', options:['ℝ','ℚ','ℤ','ℕ'], answer:0 },
{ id:'M1.02.c02', clause:'M1.02', course:'M1', yield:2, type:'CLASSIFY',
  prompt:'Cantor’s diagonal argument establishes that…',
  options:['ℝ is uncountable','ℚ is countable','ℤ is countable','ℕ is infinite'], answer:0 },
{ id:'M1.02.f07', clause:'M1.02', course:'M1', yield:2, type:'FORMULA',
  prompt:'|A × B| in terms of |A| and |B|', answer:'|A||B|', accept:['|A|*|B|','|A| x |B|'] },
{ id:'M1.02.d01', clause:'M1.02', course:'M1', yield:2, type:'DERIVE',
  prompt:'Russell’s collection R = {X : X ∉ X} — state the contradiction it produces.',
  answer:'R∈R iff R∉R', accept:['R is a member of itself exactly when it is not'] },

/* ── M1.03 Relations ─ yield 1 ─────────────────────────────────────── */
{ id:'M1.03.f01', clause:'M1.03', course:'M1', yield:1, type:'FORMULA',
  prompt:'Number of relations on a set A with |A| = n', answer:'2^(n^2)', accept:['2^n^2','2**(n*n)'] },
{ id:'M1.03.c01', clause:'M1.03', course:'M1', yield:1, type:'CLASSIFY',
  prompt:'Reflexive + symmetric + transitive defines a…',
  options:['equivalence relation','partial order','total order','function'], answer:0 },
{ id:'M1.03.c02', clause:'M1.03', course:'M1', yield:1, type:'CLASSIFY',
  prompt:'Reflexive + antisymmetric + transitive defines a…',
  options:['partial order','equivalence relation','bijection','partition'], answer:0 },
{ id:'M1.03.dsc01', clause:'M1.03', course:'M1', yield:1, type:'DISCRIM',
  left:'Symmetric', right:'Antisymmetric',
  items:[{t:'aRb ⇒ bRa', side:'L'},{t:'aRb ∧ bRa ⇒ a = b', side:'R'},
         {t:'“is a sibling of”', side:'L'},{t:'“is less than or equal to”', side:'R'},
         {t:'Equivalence relations require it', side:'L'},{t:'Partial orders require it', side:'R'}] },
{ id:'M1.03.t01', clause:'M1.03', course:'M1', yield:1, type:'TRAP',
  claim:'The equivalence classes of an equivalence relation on A partition A.', verdict:true, because:'partition',
  reasons:[{k:'partition',label:'they are non-empty, pairwise disjoint, and cover A'},{k:'overlap',label:'they may overlap'},{k:'notcover',label:'they need not cover A'},{k:'onlyfinite',label:'this holds only for finite A'}] },

/* ── M1.04 Functions ─ yield 2 ─────────────────────────────────────── */
{ id:'M1.04.f01', clause:'M1.04', course:'M1', yield:2, type:'FORMULA',
  prompt:'Number of functions A → B where |A| = m, |B| = n', answer:'n^m', accept:['n**m'] },
{ id:'M1.04.f02', clause:'M1.04', course:'M1', yield:2, type:'FORMULA',
  prompt:'Number of injective functions A → B, |A| = m, |B| = n',
  answer:'n(n-1)...(n-m+1)', accept:['n!/(n-m)!','nPm','P(n,m)'] },
{ id:'M1.04.f03', clause:'M1.04', course:'M1', yield:2, type:'FORMULA',
  prompt:'Number of surjective functions A → B, |A| = m, |B| = n',
  answer:'sum_{k=0}^{n}(-1)^k C(n,k)(n-k)^m', accept:['sum (-1)^k nCk (n-k)^m'] },
{ id:'M1.04.f04', clause:'M1.04', course:'M1', yield:2, type:'FORMULA',
  prompt:'Inverse of a composition: (g ∘ f)⁻¹ = ?', answer:'f^-1∘g^-1', accept:['f inverse composed with g inverse','f^{-1} o g^{-1}'] },
{ id:'M1.04.c01', clause:'M1.04', course:'M1', yield:2, type:'CLASSIFY',
  prompt:'f⁻¹ exists exactly when f is…',
  options:['a bijection','injective only','surjective only','continuous'], answer:0 },
{ id:'M1.04.c02', clause:'M1.04', course:'M1', yield:2, type:'CLASSIFY',
  prompt:'The graph of f⁻¹ is the graph of f reflected in which line?',
  options:['y = x','the x-axis','the y-axis','y = −x'], answer:0 },
{ id:'M1.04.c03', clause:'M1.04', course:'M1', yield:2, type:'CLASSIFY',
  prompt:'f(−x) = −f(x) describes a function that is…',
  options:['odd, symmetric about the origin','even, symmetric about the y-axis','increasing','periodic'], answer:0 },
{ id:'M1.04.dsc01', clause:'M1.04', course:'M1', yield:2, type:'DISCRIM',
  left:'Injective (one-one)', right:'Surjective (onto)',
  items:[{t:'f(x₁)=f(x₂) ⇒ x₁=x₂', side:'L'},{t:'f(A) = B', side:'R'},
         {t:'Horizontal line meets graph at most once', side:'L'},{t:'Every element of the codomain is hit', side:'R'},
         {t:'A strictly monotone function is automatically this', side:'L'},{t:'Requires the image to fill the codomain', side:'R'}] },
{ id:'M1.04.ch01', clause:'M1.04', course:'M1', yield:2, type:'CHAIN',
  prompt:'Transformations of y = f(x): order these from the graph of f to the graph of a·f(x + k) + c',
  steps:['Shift left by k: f(x + k)','Stretch vertically by a: a·f(x + k)','Shift up by c: a·f(x + k) + c'] },
{ id:'M1.04.t01', clause:'M1.04', course:'M1', yield:2, type:'TRAP',
  claim:'Composition of functions is commutative.', verdict:false, because:'notcomm',
  reasons:[{k:'notcomm',label:'g∘f ≠ f∘g in general; composition is associative but not commutative'},{k:'nonassoc',label:'composition is not associative'},{k:'onlybij',label:'it commutes only for bijections'},{k:'true',label:'it is in fact commutative'}] },

/* ── M1.05 Coordinate geometry ─ yield 2 ───────────────────────────── */
{ id:'M1.05.f01', clause:'M1.05', course:'M1', yield:2, type:'FORMULA',
  prompt:'Distance between (x₁,y₁) and (x₂,y₂)',
  answer:'sqrt((x2-x1)^2+(y2-y1)^2)', accept:['root((x2-x1)^2+(y2-y1)^2)'] },
{ id:'M1.05.f02', clause:'M1.05', course:'M1', yield:2, type:'FORMULA',
  prompt:'Internal section formula, ratio m:n — the point is…',
  answer:'((m x2+n x1)/(m+n),(m y2+n y1)/(m+n))', accept:['((mx2+nx1)/(m+n),(my2+ny1)/(m+n))'] },
{ id:'M1.05.f03', clause:'M1.05', course:'M1', yield:2, type:'FORMULA',
  prompt:'External section formula, ratio m:n',
  answer:'((m x2-n x1)/(m-n),(m y2-n y1)/(m-n))', accept:['((mx2-nx1)/(m-n),(my2-ny1)/(m-n))'] },
{ id:'M1.05.f04', clause:'M1.05', course:'M1', yield:2, type:'FORMULA',
  prompt:'Centroid of a triangle with vertices (xᵢ,yᵢ)',
  answer:'((x1+x2+x3)/3,(y1+y2+y3)/3)', accept:['average of the three vertices'] },
{ id:'M1.05.f05', clause:'M1.05', course:'M1', yield:2, type:'FORMULA',
  prompt:'Area of a triangle from three vertices',
  answer:'(1/2)|x1(y2-y3)+x2(y3-y1)+x3(y1-y2)|', accept:['1/2 |x1(y2-y3)+x2(y3-y1)+x3(y1-y2)|'] },
{ id:'M1.05.co01', clause:'M1.05', course:'M1', yield:2, type:'CONDITION',
  prompt:'Area of a triangle computed as ½[x₁(y₂−y₃)+x₂(y₃−y₁)+x₃(y₁−y₂)], answer left negative.',
  verdict:'reject', because:'modulus',
  reasons:[{k:'modulus',label:'the modulus must be taken — area is non-negative'},{k:'wrongform',label:'the formula itself is wrong'},{k:'needsorder',label:'vertices must be listed clockwise'},{k:'ok',label:'nothing is wrong'}] },
{ id:'M1.05.co02', clause:'M1.05', course:'M1', yield:2, type:'CONDITION',
  prompt:'Section formula, ratio m:n — m is attached to the point (x₁,y₁).',
  verdict:'reject', because:'farpoint',
  reasons:[{k:'farpoint',label:'m attaches to the far point (x₂,y₂)'},{k:'swapratio',label:'the ratio must be inverted first'},{k:'external',label:'this only holds for external division'},{k:'ok',label:'nothing is wrong'}] },
{ id:'M1.05.c01', clause:'M1.05', course:'M1', yield:2, type:'CLASSIFY',
  prompt:'Three points are collinear exactly when the triangle area Δ equals…',
  options:['0','1','∞','½'], answer:0 },

/* ── M1.06 Straight lines ─ yield 3 (highest) ──────────────────────── */
{ id:'M1.06.f01', clause:'M1.06', course:'M1', yield:3, type:'FORMULA',
  prompt:'Slope from two points, and its trigonometric meaning',
  answer:'m=(y2-y1)/(x2-x1)=tan(theta)', accept:['(y2-y1)/(x2-x1)','tan theta'] },
{ id:'M1.06.f02', clause:'M1.06', course:'M1', yield:3, type:'FORMULA',
  prompt:'Point–slope form of a line', answer:'y-y1=m(x-x1)', accept:['y − y₁ = m(x − x₁)'] },
{ id:'M1.06.f03', clause:'M1.06', course:'M1', yield:3, type:'FORMULA',
  prompt:'Two-point form of a line', answer:'y-y1=((y2-y1)/(x2-x1))(x-x1)', accept:['y-y1=(y2-y1)/(x2-x1)*(x-x1)'] },
{ id:'M1.06.f04', clause:'M1.06', course:'M1', yield:3, type:'FORMULA',
  prompt:'Slope–intercept form of a line', answer:'y=mx+c', accept:['y=mx+b'] },
{ id:'M1.06.f05', clause:'M1.06', course:'M1', yield:3, type:'FORMULA',
  prompt:'Intercept form of a line', answer:'x/a+y/b=1', accept:['(x/a)+(y/b)=1'] },
{ id:'M1.06.f06', clause:'M1.06', course:'M1', yield:3, type:'FORMULA',
  prompt:'Normal form of a line (perpendicular distance p from the origin)',
  answer:'x cos(alpha)+y sin(alpha)=p', accept:['xcosa+ysina=p'] },
{ id:'M1.06.f07', clause:'M1.06', course:'M1', yield:3, type:'FORMULA',
  prompt:'General form of a line', answer:'Ax+By+C=0', accept:['ax+by+c=0'] },
{ id:'M1.06.f08', clause:'M1.06', course:'M1', yield:3, type:'FORMULA',
  prompt:'From Ax + By + C = 0, read off the slope m',
  answer:'-A/B', accept:['-(A/B)'] },
{ id:'M1.06.f09', clause:'M1.06', course:'M1', yield:3, type:'FORMULA',
  prompt:'From Ax + By + C = 0, give the x-intercept and the y-intercept',
  answer:'x-int=-C/A, y-int=-C/B', accept:['-C/A and -C/B'] },
{ id:'M1.06.f10', clause:'M1.06', course:'M1', yield:3, type:'FORMULA',
  prompt:'Perpendicular distance from (x₀,y₀) to Ax + By + C = 0',
  answer:'|A x0+B y0+C|/sqrt(A^2+B^2)', accept:['|Ax0+By0+C|/sqrt(A^2+B^2)','|ax0+by0+c|/root(a^2+b^2)'] },
{ id:'M1.06.f11', clause:'M1.06', course:'M1', yield:3, type:'FORMULA',
  prompt:'Distance between the parallels Ax + By + C₁ = 0 and Ax + By + C₂ = 0',
  answer:'|C1-C2|/sqrt(A^2+B^2)', accept:['|c1-c2|/root(a^2+b^2)'] },
{ id:'M1.06.f12', clause:'M1.06', course:'M1', yield:3, type:'FORMULA',
  prompt:'Angle between two lines with slopes m₁ and m₂',
  answer:'tan(theta)=|(m1-m2)/(1+m1 m2)|', accept:['|(m1-m2)/(1+m1m2)|'] },
{ id:'M1.06.f13', clause:'M1.06', course:'M1', yield:3, type:'FORMULA',
  prompt:'Line through (x₁,y₁) perpendicular to Ax + By + C = 0',
  answer:'B(x-x1)-A(y-y1)=0', accept:['Bx-Ay+k=0 through the point'] },
{ id:'M1.06.c01', clause:'M1.06', course:'M1', yield:3, type:'CLASSIFY',
  prompt:'Two non-vertical lines are perpendicular exactly when…',
  options:['m₁m₂ = −1','m₁ = m₂','m₁ + m₂ = 0','m₁m₂ = 1'], answer:0 },
{ id:'M1.06.c02', clause:'M1.06', course:'M1', yield:3, type:'CLASSIFY',
  prompt:'A₁x+B₁y+C₁=0 and A₂x+B₂y+C₂=0 are parallel (not identical) when…',
  options:['A₁/A₂ = B₁/B₂ ≠ C₁/C₂','all three ratios are equal','A₁A₂ + B₁B₂ = 0','A₁/B₁ = A₂/B₂ = C₁/C₂'], answer:0 },
{ id:'M1.06.co01', clause:'M1.06', course:'M1', yield:3, type:'CONDITION',
  prompt:'Apply the point-to-line distance formula directly to the line written as y = 3x + 2.',
  verdict:'reject', because:'general',
  reasons:[{k:'general',label:'rewrite in general form with everything on one side first'},{k:'slope',label:'the slope must be positive'},{k:'origin',label:'the line must pass through the origin'},{k:'ok',label:'nothing is wrong'}] },
{ id:'M1.06.co02', clause:'M1.06', course:'M1', yield:3, type:'CONDITION',
  prompt:'Use d = |C₁−C₂|/√(A²+B²) for 2x + 3y + 1 = 0 and 4x + 6y + 7 = 0.',
  verdict:'reject', because:'rescale',
  reasons:[{k:'rescale',label:'A and B must be identical — rescale one equation first'},{k:'notparallel',label:'the lines are not parallel'},{k:'signs',label:'the signs of C must match'},{k:'ok',label:'nothing is wrong'}] },
{ id:'M1.06.co03', clause:'M1.06', course:'M1', yield:3, type:'CONDITION',
  prompt:'Use m₁m₂ = −1 to test perpendicularity when one of the lines is vertical.',
  verdict:'reject', because:'vertical',
  reasons:[{k:'vertical',label:'the slope of a vertical line is undefined — handle that case separately'},{k:'horizontal',label:'horizontal lines break the test'},{k:'sign',label:'the product should be +1'},{k:'ok',label:'nothing is wrong'}] },
{ id:'M1.06.t01', clause:'M1.06', course:'M1', yield:3, type:'TRAP',
  claim:'The least-squares line always passes through (x̄, ȳ).', verdict:true, because:'always',
  reasons:[{k:'always',label:'it is a property of the least-squares fit'},{k:'onlyr1',label:'only when r = 1'},{k:'onlycentred',label:'only when the data is centred'},{k:'never',label:'it generally does not'}] },

/* ── M1.07 Quadratics ─ yield 3 (highest) ──────────────────────────── */
{ id:'M1.07.f01', clause:'M1.07', course:'M1', yield:3, type:'FORMULA',
  prompt:'The quadratic formula for ax² + bx + c = 0',
  answer:'x=(-b±sqrt(b^2-4ac))/(2a)', accept:['(-b+-sqrt(b^2-4ac))/(2a)','(-b±√(b²−4ac))/2a'] },
{ id:'M1.07.f02', clause:'M1.07', course:'M1', yield:3, type:'FORMULA',
  prompt:'Vertex of y = ax² + bx + c, in terms of b, a and D',
  answer:'(-b/(2a),-D/(4a))', accept:['(-b/2a, -D/4a)'] },
{ id:'M1.07.f03', clause:'M1.07', course:'M1', yield:3, type:'FORMULA',
  prompt:'Axis of symmetry of a parabola y = ax² + bx + c',
  answer:'x=-b/(2a)', accept:['x = -b/2a'] },
{ id:'M1.07.f04', clause:'M1.07', course:'M1', yield:3, type:'FORMULA',
  prompt:'The discriminant D of ax² + bx + c', answer:'b^2-4ac', accept:['b²−4ac'] },
{ id:'M1.07.f05', clause:'M1.07', course:'M1', yield:3, type:'FORMULA',
  prompt:'Sum and product of the roots α, β of ax² + bx + c = 0',
  answer:'alpha+beta=-b/a, alpha*beta=c/a', accept:['-b/a and c/a'] },
{ id:'M1.07.f06', clause:'M1.07', course:'M1', yield:3, type:'FORMULA',
  prompt:'|α − β| in terms of D and a', answer:'sqrt(D)/|a|', accept:['√D/|a|'] },
{ id:'M1.07.f07', clause:'M1.07', course:'M1', yield:3, type:'FORMULA',
  prompt:'Reconstruct a quadratic from its roots α and β',
  answer:'x^2-(alpha+beta)x+alpha*beta=0', accept:['x² − (α+β)x + αβ = 0'] },
{ id:'M1.07.f08', clause:'M1.07', course:'M1', yield:3, type:'FORMULA',
  prompt:'α² + β² expressed using the sum and product of the roots',
  answer:'(alpha+beta)^2-2*alpha*beta', accept:['(α+β)² − 2αβ'] },
{ id:'M1.07.f09', clause:'M1.07', course:'M1', yield:3, type:'FORMULA',
  prompt:'Tangent slope (derivative) of f(x) = ax² + bx + c',
  answer:'2ax+b', accept:['f\'(x)=2ax+b'] },
{ id:'M1.07.c01', clause:'M1.07', course:'M1', yield:3, type:'CLASSIFY',
  prompt:'D = 0 means the graph does what to the x-axis?',
  options:['touches it (tangent)','cuts it twice','misses it entirely','crosses three times'], answer:0 },
{ id:'M1.07.c02', clause:'M1.07', course:'M1', yield:3, type:'CLASSIFY',
  prompt:'D < 0 with real coefficients means the roots are…',
  options:['a complex conjugate pair','two distinct reals','one repeated real','rational'], answer:0 },
{ id:'M1.07.c03', clause:'M1.07', course:'M1', yield:3, type:'CLASSIFY',
  prompt:'a > 0: the vertex is the … and the range is …',
  options:['minimum; [−D/4a, ∞)','maximum; (−∞, −D/4a]','minimum; (−∞, ∞)','maximum; [−D/4a, ∞)'], answer:0 },
{ id:'M1.07.c04', clause:'M1.07', course:'M1', yield:3, type:'CLASSIFY',
  prompt:'If D > 0 with roots α < β, then f has the sign of a…',
  options:['outside [α, β], opposite sign strictly inside','inside [α, β] only','everywhere','nowhere'], answer:0 },
{ id:'M1.07.ch01', clause:'M1.07', course:'M1', yield:3, type:'CHAIN',
  prompt:'Derive the quadratic formula by completing the square — order the steps',
  steps:['Factor a out of the x terms: a(x² + (b/a)x) + c',
         'Complete the square: a(x + b/2a)² − b²/4a + c',
         'Set to zero and isolate: (x + b/2a)² = (b² − 4ac)/4a²',
         'Take square roots and solve: x = (−b ± √(b² − 4ac))/2a'] },
{ id:'M1.07.d01', clause:'M1.07', course:'M1', yield:3, type:'DERIVE',
  prompt:'Why is the vertex the extremum? Give the algebraic reason.',
  answer:'f\'(x)=2ax+b is zero exactly at x=-b/2a', accept:['the tangent slope 2ax+b vanishes at the vertex'] },

/* ── M1.08 Polynomials ─ yield 2 ───────────────────────────────────── */
{ id:'M1.08.f01', clause:'M1.08', course:'M1', yield:2, type:'FORMULA',
  prompt:'Degree of a product: deg(pq) = ?', answer:'deg p+deg q', accept:['deg(p)+deg(q)'] },
{ id:'M1.08.f02', clause:'M1.08', course:'M1', yield:2, type:'FORMULA',
  prompt:'Division algorithm for polynomials: p(x) = ?',
  answer:'q(x)s(x)+r(x) with deg r<deg q', accept:['q*s+r, deg r < deg q'] },
{ id:'M1.08.f03', clause:'M1.08', course:'M1', yield:2, type:'FORMULA',
  prompt:'Remainder theorem: dividing p(x) by (x − a) leaves remainder…',
  answer:'p(a)', accept:['p of a'] },
{ id:'M1.08.f04', clause:'M1.08', course:'M1', yield:2, type:'FORMULA',
  prompt:'Remainder on dividing p(x) by (ax − b)', answer:'p(b/a)', accept:['p of b over a'] },
{ id:'M1.08.f05', clause:'M1.08', course:'M1', yield:2, type:'FORMULA',
  prompt:'Vieta for degree n: sum of roots and product of roots',
  answer:'sum=-a_{n-1}/a_n, prod=(-1)^n a_0/a_n', accept:['-a(n-1)/an and (-1)^n a0/an'] },
{ id:'M1.08.c01', clause:'M1.08', course:'M1', yield:2, type:'CLASSIFY',
  prompt:'Factor theorem: (x − a) divides p(x) exactly when…',
  options:['p(a) = 0','p(0) = a','p′(a) = 0','a divides the constant term'], answer:0 },
{ id:'M1.08.c02', clause:'M1.08', course:'M1', yield:2, type:'CLASSIFY',
  prompt:'At a root of even multiplicity the graph…',
  options:['touches the axis','crosses the axis','has a vertical asymptote','is undefined'], answer:0 },
{ id:'M1.08.c03', clause:'M1.08', course:'M1', yield:2, type:'CLASSIFY',
  prompt:'Rational root p/q (lowest terms) of an integer-coefficient polynomial satisfies…',
  options:['p | a₀ and q | aₙ','p | aₙ and q | a₀','p = q','p + q divides a₀'], answer:0 },
{ id:'M1.08.t01', clause:'M1.08', course:'M1', yield:2, type:'TRAP',
  claim:'An odd-degree polynomial with real coefficients always has at least one real root.', verdict:true, because:'conjpairs',
  reasons:[{k:'conjpairs',label:'non-real roots come in conjugate pairs, so an odd count leaves one real'},{k:'fta',label:'the fundamental theorem of algebra says all roots are real'},{k:'ivt',label:'only continuous polynomials have this property'},{k:'false',label:'it may have no real roots'}] },
{ id:'M1.08.t02', clause:'M1.08', course:'M1', yield:2, type:'TRAP',
  claim:'deg(p + q) = max(deg p, deg q) always.', verdict:false, because:'cancel',
  reasons:[{k:'cancel',label:'leading terms can cancel, so only ≤ holds'},{k:'sum',label:'degrees add under addition'},{k:'min',label:'it is the minimum, not the maximum'},{k:'true',label:'equality always holds'}] },
{ id:'M1.08.c04', clause:'M1.08', course:'M1', yield:2, type:'CLASSIFY',
  prompt:'A degree-n polynomial has exactly how many roots in ℂ (with multiplicity)?',
  options:['n','n − 1','at most n/2','it varies'], answer:0 }

]);
