/* FOUNDATION 44 — Corpus: Mathematics for Data Science II
   Source clauses M2.01 … M2.12 of the Foundation Theory Handbook. */
window.CORPUS = (window.CORPUS || []).concat([

/* ── M2.01 Vectors and matrices ─ yield 2 ──────────────────────────── */
{ id:'M2.01.f01', clause:'M2.01', course:'M2', yield:2, type:'FORMULA',
  prompt:'Dot product of u and v, in sum and matrix notation',
  answer:'sum u_i v_i = u^T v', accept:['Σuᵢvᵢ = uᵀv'] },
{ id:'M2.01.f02', clause:'M2.01', course:'M2', yield:2, type:'FORMULA',
  prompt:'Angle between two vectors: cos θ = ?',
  answer:'(u·v)/(||u|| ||v||)', accept:['u dot v / (norm u * norm v)'] },
{ id:'M2.01.f03', clause:'M2.01', course:'M2', yield:2, type:'FORMULA',
  prompt:'Transpose of a product: (AB)ᵀ = ?', answer:'B^T A^T', accept:['BᵀAᵀ'] },
{ id:'M2.01.f04', clause:'M2.01', course:'M2', yield:2, type:'FORMULA',
  prompt:'Inverse of a product: (AB)⁻¹ = ?', answer:'B^-1 A^-1', accept:['B⁻¹A⁻¹'] },
{ id:'M2.01.f05', clause:'M2.01', course:'M2', yield:2, type:'FORMULA',
  prompt:'Entry (i,j) of the matrix product AB', answer:'sum_k a_ik b_kj', accept:['Σₖ aᵢₖbₖⱼ'] },
{ id:'M2.01.f06', clause:'M2.01', course:'M2', yield:2, type:'FORMULA',
  prompt:'Trace identity relating tr(AB) and tr(BA)', answer:'tr(AB)=tr(BA)', accept:['they are equal'] },
{ id:'M2.01.f07', clause:'M2.01', course:'M2', yield:2, type:'FORMULA',
  prompt:'Split any square A uniquely into symmetric + skew parts',
  answer:'A=(1/2)(A+A^T)+(1/2)(A-A^T)', accept:['½(A+Aᵀ) + ½(A−Aᵀ)'] },
{ id:'M2.01.c01', clause:'M2.01', course:'M2', yield:2, type:'CLASSIFY',
  prompt:'An orthogonal matrix satisfies…',
  options:['AᵀA = I, so A⁻¹ = Aᵀ','A² = A','Aᵀ = −A','det A = 0'], answer:0 },
{ id:'M2.01.c02', clause:'M2.01', course:'M2', yield:2, type:'CLASSIFY',
  prompt:'A skew-symmetric matrix has which diagonal entries?',
  options:['all zero','all one','all equal','unconstrained'], answer:0 },
{ id:'M2.01.c03', clause:'M2.01', course:'M2', yield:2, type:'CLASSIFY',
  prompt:'Idempotent means…', options:['A² = A','A² = I','Aᵀ = A','A⁻¹ = A'], answer:0 },
{ id:'M2.01.t01', clause:'M2.01', course:'M2', yield:2, type:'TRAP',
  claim:'AB = 0 implies A = 0 or B = 0.', verdict:false, because:'zerodiv',
  reasons:[{k:'zerodiv',label:'matrices have zero divisors — neither factor need vanish'},{k:'true',label:'the statement is correct'},{k:'square',label:'it holds only for square matrices'},{k:'inv',label:'it holds only if A is invertible'}] },
{ id:'M2.01.t02', clause:'M2.01', course:'M2', yield:2, type:'TRAP',
  claim:'AB = AC implies B = C.', verdict:false, because:'needinv',
  reasons:[{k:'needinv',label:'cancellation requires A to be invertible'},{k:'true',label:'the statement is correct'},{k:'square',label:'it holds for all square A'},{k:'sym',label:'it holds when A is symmetric'}] },

/* ── M2.02 Linear systems and RREF ─ yield 3 ───────────────────────── */
{ id:'M2.02.f01', clause:'M2.02', course:'M2', yield:3, type:'FORMULA',
  prompt:'The three elementary row operations',
  answer:'swap rows; scale a row by c≠0; add a multiple of one row to another',
  accept:['Ri<->Rj; Ri->cRi; Ri->Ri+cRj'] },
{ id:'M2.02.f02', clause:'M2.02', course:'M2', yield:3, type:'FORMULA',
  prompt:'Structure of the solution set of Ax = b',
  answer:'x_p + N(A)', accept:['one particular solution plus the null space'] },
{ id:'M2.02.c01', clause:'M2.02', course:'M2', yield:3, type:'CLASSIFY',
  prompt:'rank(A) < rank([A|b]) means the system has…',
  options:['no solution','a unique solution','infinitely many solutions','the trivial solution only'], answer:0 },
{ id:'M2.02.c02', clause:'M2.02', course:'M2', yield:3, type:'CLASSIFY',
  prompt:'rank(A) = rank([A|b]) = n (number of unknowns) means…',
  options:['a unique solution','no solution','infinitely many','undetermined'], answer:0 },
{ id:'M2.02.c03', clause:'M2.02', course:'M2', yield:3, type:'CLASSIFY',
  prompt:'rank(A) = rank([A|b]) = r < n means infinitely many solutions with how many free parameters?',
  options:['n − r','r','n','r − n'], answer:0 },
{ id:'M2.02.c04', clause:'M2.02', course:'M2', yield:3, type:'CLASSIFY',
  prompt:'A homogeneous system Ax = 0 has a non-trivial solution exactly when…',
  options:['rank(A) < n','rank(A) = n','det A ≠ 0','m > n'], answer:0 },
{ id:'M2.02.c05', clause:'M2.02', course:'M2', yield:3, type:'CLASSIFY',
  prompt:'The RREF of a matrix is…',
  options:['unique','one of many valid forms','never unique','unique only for square matrices'], answer:0 },
{ id:'M2.02.ch01', clause:'M2.02', course:'M2', yield:3, type:'CHAIN',
  prompt:'Gauss–Jordan: from a system to its full solution set',
  steps:['Write the augmented matrix [A | b]','Row-reduce to reduced row echelon form',
         'Identify pivot columns (basic variables) and non-pivot columns (free variables)',
         'Set each free variable to a parameter','Express the basic variables in terms of those parameters'] },
{ id:'M2.02.ch02', clause:'M2.02', course:'M2', yield:3, type:'CHAIN',
  prompt:'Finding an inverse by row reduction',
  steps:['Form the augmented block [A | I]','Row-reduce the left block toward I',
         'If a zero row appears on the left, stop — A is singular',
         'Otherwise read the inverse off the right block: [I | A⁻¹]'] },
{ id:'M2.02.f03', clause:'M2.02', course:'M2', yield:3, type:'FORMULA',
  prompt:'List four equivalent statements to “A (n×n) is invertible”',
  answer:'det A≠0; rank A=n; RREF is I; Ax=0 has only the trivial solution',
  accept:['columns independent; columns span R^n; nullity 0; product of elementary matrices'] },
{ id:'M2.02.co01', clause:'M2.02', course:'M2', yield:3, type:'CONDITION',
  prompt:'Row operations were applied, then the column space was read off the reduced matrix’s columns.',
  verdict:'reject', because:'colspacechanges',
  reasons:[{k:'colspacechanges',label:'row operations change the column space — use the ORIGINAL matrix’s pivot columns'},{k:'rowchanges',label:'row operations change the row space'},{k:'nullchanges',label:'row operations change the null space'},{k:'ok',label:'nothing is wrong'}] },
{ id:'M2.02.t01', clause:'M2.02', course:'M2', yield:3, type:'TRAP',
  claim:'A homogeneous system with more unknowns than equations always has a non-trivial solution.', verdict:true, because:'mltn',
  reasons:[{k:'mltn',label:'m < n forces rank(A) < n, so free variables exist'},{k:'never',label:'it may have only the trivial solution'},{k:'square',label:'this holds only for square systems'},{k:'det',label:'it depends on the determinant'}] },

/* ── M2.03 Determinants ─ yield 2 ──────────────────────────────────── */
{ id:'M2.03.f01', clause:'M2.03', course:'M2', yield:2, type:'FORMULA',
  prompt:'Determinant of a 2×2 matrix [[a,b],[c,d]]', answer:'ad-bc', accept:['ad − bc'] },
{ id:'M2.03.f02', clause:'M2.03', course:'M2', yield:2, type:'FORMULA',
  prompt:'Cofactor C_ij in terms of the minor M_ij', answer:'(-1)^(i+j) M_ij', accept:['(−1)^{i+j}M_{ij}'] },
{ id:'M2.03.f03', clause:'M2.03', course:'M2', yield:2, type:'FORMULA',
  prompt:'det(kA) for an n×n matrix', answer:'k^n det A', accept:['kⁿ·det A'] },
{ id:'M2.03.f04', clause:'M2.03', course:'M2', yield:2, type:'FORMULA',
  prompt:'Inverse via the adjugate', answer:'A^-1=(1/det A) adj(A)', accept:['adj(A)/det A'] },
{ id:'M2.03.f05', clause:'M2.03', course:'M2', yield:2, type:'FORMULA',
  prompt:'Cramer’s rule for xᵢ', answer:'x_i=det(A_i)/det(A)', accept:['det Aᵢ / det A'] },
{ id:'M2.03.f06', clause:'M2.03', course:'M2', yield:2, type:'FORMULA',
  prompt:'Determinant of a triangular or diagonal matrix', answer:'product of the diagonal entries', accept:['prod a_ii'] },
{ id:'M2.03.c01', clause:'M2.03', course:'M2', yield:2, type:'CLASSIFY',
  prompt:'Adding a multiple of one row to another does what to the determinant?',
  options:['leaves it unchanged','flips its sign','scales it','makes it zero'], answer:0 },
{ id:'M2.03.c02', clause:'M2.03', course:'M2', yield:2, type:'CLASSIFY',
  prompt:'Swapping two rows does what to the determinant?',
  options:['flips its sign','leaves it unchanged','doubles it','zeroes it'], answer:0 },
{ id:'M2.03.c03', clause:'M2.03', course:'M2', yield:2, type:'CLASSIFY',
  prompt:'Geometrically, |det A| is…',
  options:['the factor by which A scales area or volume','the length of the longest column','the number of pivots','always 1'], answer:0 },
{ id:'M2.03.t01', clause:'M2.03', course:'M2', yield:2, type:'TRAP',
  claim:'det(A + B) = det A + det B.', verdict:false, because:'notadditive',
  reasons:[{k:'notadditive',label:'the determinant is multiplicative, not additive'},{k:'true',label:'the statement is correct'},{k:'square',label:'it holds for square matrices only'},{k:'sym',label:'it holds for symmetric matrices'}] },
{ id:'M2.03.co01', clause:'M2.03', course:'M2', yield:2, type:'CONDITION',
  prompt:'Apply Cramer’s rule to a 3×4 system.', verdict:'reject', because:'squareonly',
  reasons:[{k:'squareonly',label:'Cramer’s rule needs a square, non-singular system — row-reduce instead'},{k:'toobig',label:'the system is too large'},{k:'singular',label:'the determinant is negative'},{k:'ok',label:'nothing is wrong'}] },
{ id:'M2.03.c04', clause:'M2.03', course:'M2', yield:2, type:'CLASSIFY',
  prompt:'A zero determinant means the transformation…',
  options:['collapses space into a lower dimension','preserves volume','is a rotation','is the identity'], answer:0 },

/* ── M2.04 Vector spaces and subspaces ─ yield 2 ────────────────────── */
{ id:'M2.04.f01', clause:'M2.04', course:'M2', yield:2, type:'FORMULA',
  prompt:'The three-part subspace test',
  answer:'0∈W; closed under addition; closed under scalar multiplication',
  accept:['contains zero and is closed under linear combinations'] },
{ id:'M2.04.f02', clause:'M2.04', course:'M2', yield:2, type:'FORMULA',
  prompt:'Dimension formula for the sum of two subspaces',
  answer:'dim(U+W)=dim U+dim W-dim(U∩W)', accept:['dimU + dimW − dim(U∩W)'] },
{ id:'M2.04.c01', clause:'M2.04', course:'M2', yield:2, type:'CLASSIFY',
  prompt:'dim of M_{m×n}, the space of m×n matrices, is…',
  options:['mn','m + n','max(m,n)','mn − 1'], answer:0 },
{ id:'M2.04.c02', clause:'M2.04', course:'M2', yield:2, type:'CLASSIFY',
  prompt:'dim of P_n, polynomials of degree ≤ n, is…',
  options:['n + 1','n','n − 1','2n'], answer:0 },
{ id:'M2.04.c03', clause:'M2.04', course:'M2', yield:2, type:'CLASSIFY',
  prompt:'The span of a set of vectors is…',
  options:['the smallest subspace containing them','never a subspace','always all of V','the set itself'], answer:0 },
{ id:'M2.04.t01', clause:'M2.04', course:'M2', yield:2, type:'TRAP',
  claim:'The union of two subspaces is a subspace.', verdict:false, because:'unionfails',
  reasons:[{k:'unionfails',label:'the union generally fails closure under addition; the intersection is fine'},{k:'true',label:'the statement is correct'},{k:'onlyR2',label:'it fails only in ℝ²'},{k:'empty',label:'the union is empty'}] },
{ id:'M2.04.co01', clause:'M2.04', course:'M2', yield:2, type:'CONDITION',
  prompt:'A plane in ℝ³ that does not pass through the origin is proposed as a subspace.',
  verdict:'reject', because:'nozero',
  reasons:[{k:'nozero',label:'it fails to contain 0 — it is an affine subspace, not a subspace'},{k:'notclosed',label:'planes are never closed under addition'},{k:'wrongdim',label:'its dimension is wrong'},{k:'ok',label:'nothing is wrong'}] },
{ id:'M2.04.c04', clause:'M2.04', course:'M2', yield:2, type:'CLASSIFY',
  prompt:'The solution set of a HOMOGENEOUS system is…',
  options:['a subspace','an affine subspace only','never a subspace','a single point always'], answer:0 },

/* ── M2.05 Linear dependence and independence ─ yield 2 ─────────────── */
{ id:'M2.05.f01', clause:'M2.05', course:'M2', yield:2, type:'FORMULA',
  prompt:'Definition of linear independence',
  answer:'c1 v1+...+ck vk=0 implies all c_i=0', accept:['only the trivial combination gives zero'] },
{ id:'M2.05.c01', clause:'M2.05', course:'M2', yield:2, type:'CLASSIFY',
  prompt:'Any set containing the zero vector is…',
  options:['dependent','independent','a basis','orthogonal'], answer:0 },
{ id:'M2.05.c02', clause:'M2.05', course:'M2', yield:2, type:'CLASSIFY',
  prompt:'More than n vectors in ℝⁿ are…',
  options:['always dependent','always independent','sometimes a basis','orthogonal'], answer:0 },
{ id:'M2.05.c03', clause:'M2.05', course:'M2', yield:2, type:'CLASSIFY',
  prompt:'Vectors as columns of A are independent exactly when…',
  options:['every column is a pivot column','A has a zero row','rank A < k','det A = 0'], answer:0 },
{ id:'M2.05.co01', clause:'M2.05', course:'M2', yield:2, type:'CONDITION',
  prompt:'To identify an independent subset of the ORIGINAL vectors, they were placed in rows and reduced.',
  verdict:'reject', because:'usecolumns',
  reasons:[{k:'usecolumns',label:'put them in columns — pivot columns identify original vectors; rows only give a basis for the span'},{k:'userows',label:'rows are correct here'},{k:'neither',label:'neither arrangement works'},{k:'ok',label:'nothing is wrong'}] },
{ id:'M2.05.t01', clause:'M2.05', course:'M2', yield:2, type:'TRAP',
  claim:'Any subset of an independent set is independent.', verdict:true, because:'subsetok',
  reasons:[{k:'subsetok',label:'independence is inherited by subsets; dependence is inherited by supersets'},{k:'false',label:'subsets can become dependent'},{k:'onlyfinite',label:'only for finite sets'},{k:'onlyRn',label:'only in ℝⁿ'}] },

/* ── M2.06 Basis, rank, dimension ─ yield 3 ────────────────────────── */
{ id:'M2.06.f01', clause:'M2.06', course:'M2', yield:3, type:'FORMULA',
  prompt:'Definition of a basis', answer:'linearly independent and spans V', accept:['independent + spanning'] },
{ id:'M2.06.f02', clause:'M2.06', course:'M2', yield:3, type:'FORMULA',
  prompt:'rank(A) equals which three things?',
  answer:'dim row space = dim column space = number of pivots in RREF',
  accept:['row rank = column rank = pivot count'] },
{ id:'M2.06.f03', clause:'M2.06', course:'M2', yield:3, type:'FORMULA',
  prompt:'Reading a ROW SPACE basis off the RREF',
  answer:'the non-zero rows of the RREF', accept:['nonzero rows of the reduced form'] },
{ id:'M2.06.f04', clause:'M2.06', course:'M2', yield:3, type:'FORMULA',
  prompt:'Reading a COLUMN SPACE basis off the RREF',
  answer:'the columns of the ORIGINAL A in the pivot positions',
  accept:['original pivot columns'] },
{ id:'M2.06.c01', clause:'M2.06', course:'M2', yield:3, type:'CLASSIFY',
  prompt:'In a space of dimension n, any n independent vectors…',
  options:['form a basis','span only a proper subspace','are dependent','are orthogonal'], answer:0 },
{ id:'M2.06.c02', clause:'M2.06', course:'M2', yield:3, type:'CLASSIFY',
  prompt:'rank(A) is bounded above by…',
  options:['min(m, n)','max(m, n)','m + n','mn'], answer:0 },
{ id:'M2.06.c03', clause:'M2.06', course:'M2', yield:3, type:'CLASSIFY',
  prompt:'dim{0}, the zero subspace, is…', options:['0','1','undefined','∞'], answer:0 },
{ id:'M2.06.dsc01', clause:'M2.06', course:'M2', yield:3, type:'DISCRIM',
  left:'Row space', right:'Column space',
  items:[{t:'Preserved by row operations', side:'L'},{t:'Changed by row operations', side:'R'},
         {t:'Lives in ℝⁿ', side:'L'},{t:'Lives in ℝᵐ', side:'R'},
         {t:'Basis = non-zero rows of the RREF', side:'L'},{t:'Basis = pivot columns of the ORIGINAL matrix', side:'R'},
         {t:'Its orthogonal complement is the null space', side:'L'},{t:'Equals the image of the map x ↦ Ax', side:'R'}] },
{ id:'M2.06.t01', clause:'M2.06', course:'M2', yield:3, type:'TRAP',
  claim:'Row rank can differ from column rank.', verdict:false, because:'alwaysequal',
  reasons:[{k:'alwaysequal',label:'row rank always equals column rank'},{k:'square',label:'they agree only for square matrices'},{k:'sym',label:'they agree only for symmetric matrices'},{k:'true',label:'they can differ'}] },

/* ── M2.07 Null space and rank–nullity ─ yield 3 ───────────────────── */
{ id:'M2.07.f01', clause:'M2.07', course:'M2', yield:3, type:'FORMULA',
  prompt:'The rank–nullity theorem', answer:'rank(A)+nullity(A)=n', accept:['rank + nullity = number of columns'] },
{ id:'M2.07.f02', clause:'M2.07', course:'M2', yield:3, type:'FORMULA',
  prompt:'Definition of the null space N(A)', answer:'{x: Ax=0}', accept:['the set of x with Ax = 0'] },
{ id:'M2.07.c01', clause:'M2.07', course:'M2', yield:3, type:'CLASSIFY',
  prompt:'The nullity equals the number of…',
  options:['free variables','pivot columns','rows','non-zero rows'], answer:0 },
{ id:'M2.07.ch01', clause:'M2.07', course:'M2', yield:3, type:'CHAIN',
  prompt:'Finding a basis for the null space N(A)',
  steps:['Reduce A to RREF','Identify pivot columns and free columns',
         'Write each basic variable in terms of the free variables',
         'Set one free variable to 1 and the rest to 0, in turn',
         'Collect one basis vector per free variable'] },
{ id:'M2.07.d01', clause:'M2.07', course:'M2', yield:3, type:'DERIVE',
  prompt:'State the one-line proof of rank–nullity.',
  answer:'every column is either a pivot column (rank) or a free column (nullity)',
  accept:['each column contributes to exactly one of rank or nullity'] },
{ id:'M2.07.t01', clause:'M2.07', course:'M2', yield:3, type:'TRAP',
  claim:'The null-space basis vectors produced by the free-variable method are automatically independent.', verdict:true, because:'unitpattern',
  reasons:[{k:'unitpattern',label:'each has a 1 where the others have 0'},{k:'orth',label:'they are orthogonal by construction'},{k:'false',label:'they may be dependent'},{k:'norm',label:'they are normalised'}] },

/* ── M2.08 Linear transformations ─ yield 3 ────────────────────────── */
{ id:'M2.08.f01', clause:'M2.08', course:'M2', yield:3, type:'FORMULA',
  prompt:'The linearity condition, in one combined equation',
  answer:'T(au+bv)=aT(u)+bT(v)', accept:['additivity and homogeneity together'] },
{ id:'M2.08.f02', clause:'M2.08', course:'M2', yield:3, type:'FORMULA',
  prompt:'Rank–nullity for a linear map T : V → W',
  answer:'dim(ker T)+dim(im T)=dim V', accept:['nullity + rank = dim V'] },
{ id:'M2.08.f03', clause:'M2.08', course:'M2', yield:3, type:'FORMULA',
  prompt:'How the matrix [T] is built from a basis of V',
  answer:'its j-th column is [T(v_j)]_C', accept:['columns are coordinate vectors of the images of the basis'] },
{ id:'M2.08.f04', clause:'M2.08', course:'M2', yield:3, type:'FORMULA',
  prompt:'Similar matrices — the defining relation', answer:'B=P^-1 A P', accept:['P⁻¹AP'] },
{ id:'M2.08.c01', clause:'M2.08', course:'M2', yield:3, type:'CLASSIFY',
  prompt:'T is injective exactly when…',
  options:['ker T = {0}','im T = W','rank T = dim W','det T = 0'], answer:0 },
{ id:'M2.08.c02', clause:'M2.08', course:'M2', yield:3, type:'CLASSIFY',
  prompt:'A fast disqualifying test for linearity is…',
  options:['check T(0) = 0','check T is continuous','check T is invertible','check det ≠ 0'], answer:0 },
{ id:'M2.08.c03', clause:'M2.08', course:'M2', yield:3, type:'CLASSIFY',
  prompt:'Similar matrices share all of the following EXCEPT…',
  options:['their entries','rank','determinant','eigenvalues'], answer:0 },
{ id:'M2.08.c04', clause:'M2.08', course:'M2', yield:3, type:'CLASSIFY',
  prompt:'An affine map x ↦ Ax + b is linear exactly when…',
  options:['b = 0','A = I','A is invertible','b ≠ 0'], answer:0 },
{ id:'M2.08.dsc01', clause:'M2.08', course:'M2', yield:3, type:'DISCRIM',
  left:'Kernel', right:'Image',
  items:[{t:'{v : T(v) = 0}', side:'L'},{t:'{T(v) : v ∈ V}', side:'R'},
         {t:'A subspace of V', side:'L'},{t:'A subspace of W', side:'R'},
         {t:'Its dimension is the nullity', side:'L'},{t:'Its dimension is the rank', side:'R'},
         {t:'Equals N(A) for T(x) = Ax', side:'L'},{t:'Equals C(A) for T(x) = Ax', side:'R'}] },
{ id:'M2.08.dsc02', clause:'M2.08', course:'M2', yield:3, type:'DISCRIM',
  left:'Similar matrices', right:'Equivalent matrices',
  items:[{t:'B = P⁻¹AP', side:'L'},{t:'B = QAP with P, Q invertible', side:'R'},
         {t:'Same transformation, different basis', side:'L'},{t:'Same rank — and that is all', side:'R'},
         {t:'Share trace and eigenvalues', side:'L'},{t:'Need not share eigenvalues', side:'R'}] },
{ id:'M2.08.t01', clause:'M2.08', course:'M2', yield:3, type:'TRAP',
  claim:'For dim V = dim W finite, injective and surjective are equivalent for a linear map.', verdict:true, because:'ranknullity',
  reasons:[{k:'ranknullity',label:'rank–nullity forces one from the other when the dimensions match'},{k:'never',label:'they are never equivalent'},{k:'infinite',label:'this holds only in infinite dimensions'},{k:'basis',label:'it depends on the chosen basis'}] },

/* ── M2.09 Inner products, norms, orthogonality ─ yield 2 ───────────── */
{ id:'M2.09.f01', clause:'M2.09', course:'M2', yield:2, type:'FORMULA',
  prompt:'The three inner-product axioms (real case)',
  answer:'symmetry; bilinearity; positive definiteness', accept:['symmetric, bilinear, positive definite'] },
{ id:'M2.09.f02', clause:'M2.09', course:'M2', yield:2, type:'FORMULA',
  prompt:'Cauchy–Schwarz inequality', answer:'|<u,v>|<=||u|| ||v||', accept:['|u·v| ≤ ‖u‖‖v‖'] },
{ id:'M2.09.f03', clause:'M2.09', course:'M2', yield:2, type:'FORMULA',
  prompt:'The parallelogram law',
  answer:'||u+v||^2+||u-v||^2=2||u||^2+2||v||^2', accept:['‖u+v‖²+‖u−v‖² = 2‖u‖²+2‖v‖²'] },
{ id:'M2.09.f04', clause:'M2.09', course:'M2', yield:2, type:'FORMULA',
  prompt:'Definition of the orthogonal complement U⊥',
  answer:'{v: <v,u>=0 for all u in U}', accept:['all vectors orthogonal to every element of U'] },
{ id:'M2.09.f05', clause:'M2.09', course:'M2', yield:2, type:'FORMULA',
  prompt:'Dimension relation for a subspace and its complement',
  answer:'dim U+dim U^perp=dim V', accept:['dimU + dimU⊥ = dimV'] },
{ id:'M2.09.f06', clause:'M2.09', course:'M2', yield:2, type:'FORMULA',
  prompt:'For a matrix, N(A) is the orthogonal complement of which space?',
  answer:'the row space', accept:['row space of A'] },
{ id:'M2.09.c01', clause:'M2.09', course:'M2', yield:2, type:'CLASSIFY',
  prompt:'Cauchy–Schwarz holds with equality exactly when u and v are…',
  options:['parallel','orthogonal','unit vectors','zero'], answer:0 },
{ id:'M2.09.t01', clause:'M2.09', course:'M2', yield:2, type:'TRAP',
  claim:'A set of non-zero pairwise orthogonal vectors is linearly independent.', verdict:true, because:'pairing',
  reasons:[{k:'pairing',label:'pairing Σcᵢvᵢ = 0 with vⱼ kills every term but cⱼ‖vⱼ‖²'},{k:'converse',label:'and the converse also holds'},{k:'false',label:'orthogonality says nothing about independence'},{k:'needsnorm',label:'they must also be unit vectors'}] },
{ id:'M2.09.t02', clause:'M2.09', course:'M2', yield:2, type:'TRAP',
  claim:'Linearly independent vectors are automatically orthogonal.', verdict:false, because:'conversefails',
  reasons:[{k:'conversefails',label:'the converse of “orthogonal ⇒ independent” fails'},{k:'true',label:'the statement is correct'},{k:'gs',label:'Gram–Schmidt makes it true'},{k:'basis',label:'it holds for bases only'}] },

/* ── M2.10 Projection and Gram–Schmidt ─ yield 3 ───────────────────── */
{ id:'M2.10.f01', clause:'M2.10', course:'M2', yield:3, type:'FORMULA',
  prompt:'Projection of v onto a single vector u',
  answer:'(<v,u>/<u,u>)u', accept:['(v·u/u·u)u'] },
{ id:'M2.10.f02', clause:'M2.10', course:'M2', yield:3, type:'FORMULA',
  prompt:'Projection of v onto a subspace with orthonormal basis {qᵢ}',
  answer:'sum_i <v,q_i> q_i', accept:['Σ⟨v,qᵢ⟩qᵢ'] },
{ id:'M2.10.f03', clause:'M2.10', course:'M2', yield:3, type:'FORMULA',
  prompt:'Projection matrix onto C(A) when A has independent columns',
  answer:'P=A(A^T A)^-1 A^T', accept:['A(AᵀA)⁻¹Aᵀ'] },
{ id:'M2.10.f04', clause:'M2.10', course:'M2', yield:3, type:'FORMULA',
  prompt:'The two properties characterising an orthogonal projection matrix',
  answer:'P^2=P and P^T=P', accept:['idempotent and symmetric'] },
{ id:'M2.10.f05', clause:'M2.10', course:'M2', yield:3, type:'FORMULA',
  prompt:'The normal equations for least squares',
  answer:'A^T A xhat=A^T b', accept:['AᵀAx̂ = Aᵀb'] },
{ id:'M2.10.f06', clause:'M2.10', course:'M2', yield:3, type:'FORMULA',
  prompt:'The Gram–Schmidt step for wⱼ',
  answer:'w_j=v_j-sum_{i<j}(<v_j,w_i>/<w_i,w_i>)w_i',
  accept:['subtract the projections onto the previous w vectors'] },
{ id:'M2.10.f07', clause:'M2.10', course:'M2', yield:3, type:'FORMULA',
  prompt:'Coordinates of v in an orthonormal basis (Parseval form)',
  answer:'v=sum <v,q_i> q_i', accept:['coefficients are the inner products'] },
{ id:'M2.10.c01', clause:'M2.10', course:'M2', yield:3, type:'CLASSIFY',
  prompt:'proj_U(v) is characterised geometrically as…',
  options:['the unique closest point of U to v','the farthest point of U','any point of U','the origin'], answer:0 },
{ id:'M2.10.co01', clause:'M2.10', course:'M2', yield:3, type:'CONDITION',
  prompt:'In Gram–Schmidt, projections are subtracted onto the ORIGINAL vectors vᵢ.',
  verdict:'reject', because:'ontow',
  reasons:[{k:'ontow',label:'subtract projections onto the already-orthogonalised wᵢ'},{k:'ontov',label:'the original vectors are correct'},{k:'normfirst',label:'normalise before projecting'},{k:'ok',label:'nothing is wrong'}] },
{ id:'M2.10.co02', clause:'M2.10', course:'M2', yield:3, type:'CONDITION',
  prompt:'Each Gram–Schmidt vector is normalised immediately, before computing the next one.',
  verdict:'reject', because:'normlast',
  reasons:[{k:'normlast',label:'normalise at the very end, or carry fractions through the whole computation'},{k:'normfirst',label:'normalising first is required'},{k:'never',label:'never normalise'},{k:'ok',label:'nothing is wrong'}] },
{ id:'M2.10.ch01', clause:'M2.10', course:'M2', yield:3, type:'CHAIN',
  prompt:'Gram–Schmidt, correctly ordered',
  steps:['Set w₁ = v₁','For each subsequent vⱼ, compute its projections onto every previous wᵢ',
         'Subtract those projections to get wⱼ','Repeat until all vectors are processed',
         'Normalise each wⱼ to qⱼ = wⱼ/‖wⱼ‖ at the end'] },
{ id:'M2.10.t01', clause:'M2.10', course:'M2', yield:3, type:'TRAP',
  claim:'If a Gram–Schmidt wⱼ comes out zero, the original set was dependent.', verdict:true, because:'dependent',
  reasons:[{k:'dependent',label:'vⱼ lay in the span of the earlier vectors'},{k:'arith',label:'it always signals an arithmetic error'},{k:'norm',label:'it means normalisation was skipped'},{k:'false',label:'a zero vector is expected'}] },

/* ── M2.11 Orthogonal transformations ─ yield 1 ────────────────────── */
{ id:'M2.11.f01', clause:'M2.11', course:'M2', yield:1, type:'FORMULA',
  prompt:'2D rotation matrix by angle θ',
  answer:'[[cos t,-sin t],[sin t,cos t]]', accept:['cos −sin ; sin cos'] },
{ id:'M2.11.f02', clause:'M2.11', course:'M2', yield:1, type:'FORMULA',
  prompt:'Reflection in the line through the origin at angle θ',
  answer:'[[cos 2t,sin 2t],[sin 2t,-cos 2t]]', accept:['cos2θ sin2θ ; sin2θ −cos2θ'] },
{ id:'M2.11.c01', clause:'M2.11', course:'M2', yield:1, type:'CLASSIFY',
  prompt:'det Q = +1 for an orthogonal Q means it is a…',
  options:['rotation','reflection','projection','shear'], answer:0 },
{ id:'M2.11.c02', clause:'M2.11', course:'M2', yield:1, type:'CLASSIFY',
  prompt:'Orthogonal transformations preserve…',
  options:['lengths, angles and distances','area only','orientation only','nothing'], answer:0 },
{ id:'M2.11.f03', clause:'M2.11', course:'M2', yield:1, type:'FORMULA',
  prompt:'Composition and inverse of rotations',
  answer:'R_a R_b=R_(a+b), R_t^-1=R_(-t)', accept:['angles add; inverse negates the angle'] },

/* ── M2.12 Multivariable functions ─ yield 1 ───────────────────────── */
{ id:'M2.12.c01', clause:'M2.12', course:'M2', yield:1, type:'CLASSIFY',
  prompt:'A level curve of f(x,y) is the set…',
  options:['f(x,y) = c','x = c','y = c','∇f = 0'], answer:0 },
{ id:'M2.12.c02', clause:'M2.12', course:'M2', yield:1, type:'CLASSIFY',
  prompt:'Closely spaced contours indicate…',
  options:['a steep region','a flat region','a saddle','a maximum'], answer:0 },
{ id:'M2.12.c03', clause:'M2.12', course:'M2', yield:1, type:'CLASSIFY',
  prompt:'z = x² − y² is which surface?',
  options:['a saddle, with hyperbolic contours','a paraboloid','a plane','a sphere'], answer:0 },
{ id:'M2.12.c04', clause:'M2.12', course:'M2', yield:1, type:'CLASSIFY',
  prompt:'z = x² + y² is which surface?',
  options:['a paraboloid, with circular contours','a saddle','a cone','a plane'], answer:0 },
{ id:'M2.12.f01', clause:'M2.12', course:'M2', yield:1, type:'FORMULA',
  prompt:'The gradient ∇f and its geometric meaning',
  answer:'(df/dx,df/dy); perpendicular to the level curve, points of steepest increase',
  accept:['vector of partials; normal to contours, direction of steepest ascent'] },
{ id:'M2.12.c05', clause:'M2.12', course:'M2', yield:1, type:'CLASSIFY',
  prompt:'∂f/∂x is computed by…',
  options:['differentiating in x while treating y as constant','differentiating in both variables','setting y = 0','integrating over y'], answer:0 }

]);
